-- =============================================
-- Migration: Add BANNER and BANNER_IMAGE tables
-- Database: ART_AND_DECOR
-- Date: 2026-05-29
-- Description: Creates BANNER table for website banners/slides,
--              and BANNER_IMAGE junction table for n-n image relationship
-- =============================================

USE `ART_AND_DECOR`;

CREATE TABLE IF NOT EXISTS `BANNER` (
    `BANNER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BANNER_TITLE` VARCHAR(256) NOT NULL,
    `BANNER_LINK` VARCHAR(512) NULL,
    `BANNER_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `BANNER_DISPLAY_ORDER` INT DEFAULT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_banner_enabled` (`BANNER_ENABLED`),
    INDEX `idx_banner_display_order` (`BANNER_DISPLAY_ORDER`)
);

CREATE TABLE IF NOT EXISTS `BANNER_IMAGE` (
    `BANNER_IMAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BANNER_ID` BIGINT NOT NULL,
    `IMAGE_ID` BIGINT NOT NULL,
    `BANNER_IMAGE_DISPLAY_ORDER` INT NOT NULL DEFAULT 0,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`BANNER_ID`) REFERENCES `BANNER`(`BANNER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE RESTRICT,
    UNIQUE KEY `idx_banner_image_unique` (`BANNER_ID`, `IMAGE_ID`),
    INDEX `idx_banner_image_banner` (`BANNER_ID`),
    INDEX `idx_banner_image_image` (`IMAGE_ID`),
    INDEX `idx_banner_image_display_order` (`BANNER_IMAGE_DISPLAY_ORDER`)
);
