-- =============================================
-- Database: ART_AND_DECOR
-- Description: E-commerce database for Art & Decor products
-- Author: Generated for ArtAndDecor Project
-- Date: January 15, 2026
-- Version: 1.0
-- =============================================

-- Create and use database
CREATE DATABASE IF NOT EXISTS `ART_AND_DECOR` 
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `ART_AND_DECOR`;

-- =============================================
-- USER MANAGEMENT TABLES
-- =============================================

-- Table: USER_PROVIDER
CREATE TABLE `USER_PROVIDER` (
    `USER_PROVIDER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_PROVIDER_NAME` VARCHAR(50) NOT NULL UNIQUE,
    `USER_PROVIDER_REMARK_EN` VARCHAR(256),
    `USER_PROVIDER_REMARK` VARCHAR(256) NOT NULL,
    `USER_PROVIDER_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_user_provider_name` (`USER_PROVIDER_NAME`)
);

-- Table: USER_ROLE
CREATE TABLE `USER_ROLE` (
    `USER_ROLE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ROLE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `USER_ROLE_REMARK_EN` VARCHAR(256),
    `USER_ROLE_REMARK` VARCHAR(256) NOT NULL,
    `USER_ROLE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_user_role_name` (`USER_ROLE_NAME`)
);

-- Table: USER
CREATE TABLE `USER` (
    `USER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_PROVIDER_ID` BIGINT NOT NULL,
    `USER_ROLE_ID` BIGINT NOT NULL,
    `USER_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `USER_NAME` VARCHAR(64) UNIQUE,
    `PASSWORD` VARCHAR(150),
    `FIRST_NAME` VARCHAR(50),
    `LAST_NAME` VARCHAR(50),
    `PHONE_NUMBER` VARCHAR(15),
    `EMAIL` VARCHAR(100),
    `IMAGE_AVATAR_NAME` VARCHAR(150),
    `SOCIAL_MEDIA` TEXT,
    `LAST_LOGIN_DT` DATETIME NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_PROVIDER_ID`) REFERENCES `USER_PROVIDER`(`USER_PROVIDER_ID`),
    FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `USER_ROLE`(`USER_ROLE_ID`),
    INDEX `idx_user_name` (`USER_NAME`),
    INDEX `idx_user_email` (`EMAIL`),
    INDEX `idx_user_phone` (`PHONE_NUMBER`)
);

-- =============================================
-- SEO MANAGEMENT TABLES
-- =============================================


-- Table: SEO_META
CREATE TABLE `SEO_META` (
    `SEO_META_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SEO_META_TITLE` VARCHAR(150) NOT NULL,
    `SEO_META_DESCRIPTION` VARCHAR(500) NOT NULL,
    `SEO_META_KEYWORDS` VARCHAR(300),
    `SEO_META_INDEX` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_FOLLOW` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_CANONICAL_URL` VARCHAR(500),
    `SEO_META_IMAGE_NAME` VARCHAR(150),
    `SEO_META_SCHEMA_TYPE` VARCHAR(50),
    `SEO_META_CUSTOM_JSON` JSON,
    `SEO_META_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_seo_meta_title` (`SEO_META_TITLE`),
    INDEX `idx_seo_meta_canonical_url` (`SEO_META_CANONICAL_URL`),
    INDEX `idx_seo_meta_keywords` (`SEO_META_KEYWORDS`(100)),
    FULLTEXT INDEX `ft_seo_meta_search` (`SEO_META_TITLE`, `SEO_META_DESCRIPTION`, `SEO_META_KEYWORDS`)
);

-- =============================================
-- IMAGE MANAGEMENT TABLES
-- =============================================

-- Table: IMAGE_CATEGORY
-- IMAGE_CATEGORY table removed as per requirements

-- Table: IMAGE_FORMAT
-- IMAGE_FORMAT table removed as per requirements

-- Table: IMAGE
CREATE TABLE `IMAGE` (
    `IMAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `IMAGE_NAME` VARCHAR(150) NOT NULL,
    `IMAGE_DISPLAY_NAME` VARCHAR(64) NOT NULL,
    `IMAGE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `IMAGE_SIZE` VARCHAR(64) NOT NULL,
    `IMAGE_REMARK_EN` VARCHAR(256),
    `IMAGE_REMARK` VARCHAR(256),
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_image_name` (`IMAGE_NAME`),
    INDEX `idx_image_display_name` (`IMAGE_DISPLAY_NAME`),
    INDEX `idx_image_slug` (`IMAGE_SLUG`)
);

-- =============================================
-- PRODUCT MANAGEMENT TABLES
-- =============================================

-- Table: PRODUCT_TYPE
CREATE TABLE `PRODUCT_TYPE` (
    `PRODUCT_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_TYPE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_TYPE_REMARK_EN` VARCHAR(256),
    `PRODUCT_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_TYPE_DISPLAY` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `PRODUCT_TYPE_IMAGE_NAME` VARCHAR(256) NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_product_type_slug` (`PRODUCT_TYPE_SLUG`),
    INDEX `idx_product_type_name` (`PRODUCT_TYPE_NAME`),
    INDEX `idx_product_type_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_CATEGORY
CREATE TABLE `PRODUCT_CATEGORY` (
    `PRODUCT_CATEGORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_CATEGORY_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_REMARK_EN` VARCHAR(256),
    `PRODUCT_CATEGORY_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_CATEGORY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_CATEGORY_DISPLAY` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `PRODUCT_TYPE_ID` BIGINT NOT NULL,
    `PRODUCT_CATEGORY_PARENT_ID` BIGINT NULL,
    `PRODUCT_CATEGORY_IMAGE_NAME` VARCHAR(256) NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`PRODUCT_TYPE_ID`) REFERENCES `PRODUCT_TYPE`(`PRODUCT_TYPE_ID`),
    FOREIGN KEY (`PRODUCT_CATEGORY_PARENT_ID`) REFERENCES `PRODUCT_CATEGORY`(`PRODUCT_CATEGORY_ID`),
    INDEX `idx_product_category_slug` (`PRODUCT_CATEGORY_SLUG`),
    INDEX `idx_product_category_name` (`PRODUCT_CATEGORY_NAME`),
    INDEX `idx_product_category_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_STATE
CREATE TABLE `PRODUCT_STATE` (
    `PRODUCT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_STATE_REMARK_EN` VARCHAR(256),
    `PRODUCT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_product_state_name` (`PRODUCT_STATE_NAME`)
);

-- Table: PRODUCT_ATTR
CREATE TABLE `PRODUCT_ATTR` (
    `PRODUCT_ATTR_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ATTR_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_ATTR_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_ATTR_REMARK_EN` VARCHAR(256),
    `PRODUCT_ATTR_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_product_attr_name` (`PRODUCT_ATTR_NAME`)
);

-- Table: PRODUCT
CREATE TABLE `PRODUCT` (
    `PRODUCT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_NAME` VARCHAR(100) NOT NULL UNIQUE,
    `PRODUCT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_ID` BIGINT NOT NULL,
    `PRODUCT_STATE_ID` BIGINT NOT NULL,
    `PRODUCT_TYPE_ID` BIGINT NOT NULL,
    `SOLD_QUANTITY` INT NOT NULL DEFAULT 0,
    `STOCK_QUANTITY` INT NOT NULL DEFAULT 0,
    `PRODUCT_DESCRIPTION` TEXT NOT NULL,
    `PRODUCT_PRICE` DECIMAL(15,2) NOT NULL,
    `PRODUCT_REMARK_EN` VARCHAR(256),
    `PRODUCT_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_CATEGORY_ID`) REFERENCES `PRODUCT_CATEGORY`(`PRODUCT_CATEGORY_ID`),
    FOREIGN KEY (`PRODUCT_STATE_ID`) REFERENCES `PRODUCT_STATE`(`PRODUCT_STATE_ID`),
    FOREIGN KEY (`PRODUCT_TYPE_ID`) REFERENCES `PRODUCT_TYPE`(`PRODUCT_TYPE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_product_name` (`PRODUCT_NAME`),
    INDEX `idx_product_slug` (`PRODUCT_SLUG`),
    INDEX `idx_product_price` (`PRODUCT_PRICE`),
    INDEX `idx_product_stock` (`STOCK_QUANTITY`),
    INDEX `idx_product_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_IMAGE
CREATE TABLE `PRODUCT_IMAGE` (
    `PRODUCT_IMAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `IMAGE_ID` BIGINT NOT NULL,
    `PRODUCT_IMAGE_REMARK_EN` VARCHAR(256),
    `PRODUCT_IMAGE_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`),
    UNIQUE KEY `idx_product_image_unique` (`PRODUCT_ID`, `IMAGE_ID`)
);

-- Table: PRODUCT_ATTRIBUTE
CREATE TABLE `PRODUCT_ATTRIBUTE` (
    `PRODUCT_ATTRIBUTE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `PRODUCT_ATTR_ID` BIGINT NOT NULL,
    `PRODUCT_ATTRIBUTE_REMARK_EN` VARCHAR(256),
    `PRODUCT_ATTRIBUTE_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_ATTRIBUTE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ATTR_ID`) REFERENCES `PRODUCT_ATTR`(`PRODUCT_ATTR_ID`),
    UNIQUE KEY `idx_product_attribute_unique` (`PRODUCT_ID`, `PRODUCT_ATTR_ID`)
);

-- =============================================
-- REVIEW SYSTEM TABLES
-- =============================================

-- Table: REVIEW
CREATE TABLE `REVIEW` (
    `REVIEW_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `PARENT_REVIEW_ID` BIGINT,
    `ROOT_REVIEW_ID` BIGINT,
    `REVIEW_LEVEL` INT NOT NULL DEFAULT 0,
    `RATING` TINYINT NOT NULL CHECK (`RATING` BETWEEN 1 AND 5),
    `REVIEW_CONTENT` TEXT NOT NULL,
    `COUNT_LIKE` INT NOT NULL DEFAULT 0,
    `IS_VISIBLE` BOOLEAN NOT NULL DEFAULT TRUE,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `CREATED_BY_ROLE_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PARENT_REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`),
    FOREIGN KEY (`ROOT_REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`),
    FOREIGN KEY (`CREATED_BY_ROLE_ID`) REFERENCES `USER_ROLE`(`USER_ROLE_ID`),
    INDEX `idx_review_product` (`PRODUCT_ID`),
    INDEX `idx_review_user` (`USER_ID`),
    INDEX `idx_review_rating` (`RATING`)
);

-- Table: PRODUCT_REVIEW_LIKE
CREATE TABLE `PRODUCT_REVIEW_LIKE` (
    `PRODUCT_REVIEW_LIKE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `REVIEW_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
    UNIQUE KEY `idx_user_review_like_unique` (`USER_ID`, `REVIEW_ID`)
);

-- =============================================
-- CART SYSTEM TABLES
-- =============================================

-- Table: CART_STATE
CREATE TABLE `CART_STATE` (
    `CART_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `CART_STATE_REMARK_EN` VARCHAR(256),
    `CART_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CART_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_cart_state_name` (`CART_STATE_NAME`)
);

-- Table: CART
CREATE TABLE `CART` (
    `CART_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `SESSION_ID` VARCHAR(100),
    `CART_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `CART_STATE_ID` BIGINT NOT NULL,
    `TOTAL_AMOUNT` INT NOT NULL DEFAULT 0,
    `CART_REMARK_EN` VARCHAR(256),
    `CART_REMARK` VARCHAR(256) NOT NULL,
    `CART_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
    FOREIGN KEY (`CART_STATE_ID`) REFERENCES `CART_STATE`(`CART_STATE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_cart_user` (`USER_ID`),
    INDEX `idx_cart_session` (`SESSION_ID`),
    INDEX `idx_cart_slug` (`CART_SLUG`),
    INDEX `idx_cart_seo_meta` (`SEO_META_ID`)
);

-- Table: CART_ITEM_STATE
CREATE TABLE `CART_ITEM_STATE` (
    `CART_ITEM_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_ITEM_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `CART_ITEM_STATE_REMARK_EN` VARCHAR(256),
    `CART_ITEM_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CART_ITEM_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_cart_item_state_name` (`CART_ITEM_STATE_NAME`)
);

-- Table: CART_ITEM
CREATE TABLE `CART_ITEM` (
    `CART_ITEM_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `CART_ITEM_QUANTITY` INT NOT NULL DEFAULT 1,
    `CART_ITEM_TOTAL_PRICE` DECIMAL(15,2) NOT NULL,
    `CART_ITEM_STATE_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`CART_ID`) REFERENCES `CART`(`CART_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`),
    FOREIGN KEY (`CART_ITEM_STATE_ID`) REFERENCES `CART_ITEM_STATE`(`CART_ITEM_STATE_ID`),
    UNIQUE KEY `idx_cart_product_unique` (`CART_ID`, `PRODUCT_ID`)
);

-- =============================================
-- ORDER MANAGEMENT TABLES
-- =============================================

-- Table: ORDER_STATE
CREATE TABLE `ORDER_STATE` (
    `ORDER_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `ORDER_STATE_REMARK_EN` VARCHAR(256),
    `ORDER_STATE_REMARK` VARCHAR(256) NOT NULL,
    `ORDER_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_order_state_name` (`ORDER_STATE_NAME`)
);

-- Table: DISCOUNT_TYPE
CREATE TABLE `DISCOUNT_TYPE` (
    `DISCOUNT_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `DISCOUNT_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `DISCOUNT_TYPE_REMARK_EN` VARCHAR(256),
    `DISCOUNT_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `DISCOUNT_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_discount_type_name` (`DISCOUNT_TYPE_NAME`)
);

-- Table: DISCOUNT
CREATE TABLE `DISCOUNT` (
    `DISCOUNT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `DISCOUNT_CODE` VARCHAR(100) NOT NULL UNIQUE,
    `DISCOUNT_NAME` VARCHAR(64) NOT NULL,
    `DISCOUNT_TYPE_ID` BIGINT NOT NULL,
    `DISCOUNT_VALUE` DECIMAL(15,2) NOT NULL,
    `MAX_DISCOUNT_AMOUNT` DECIMAL(15,2) NOT NULL,
    `MIN_ORDER_AMOUNT` DECIMAL(15,2) NOT NULL,
    `START_AT` DATETIME NOT NULL,
    `END_AT` DATETIME NOT NULL,
    `TOTAL_USAGE_LIMIT` INT NOT NULL,
    `USED_COUNT` INT NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `DISCOUNT_REMARK_EN` VARCHAR(256),
    `DISCOUNT_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`DISCOUNT_TYPE_ID`) REFERENCES `DISCOUNT_TYPE`(`DISCOUNT_TYPE_ID`),
    INDEX `idx_discount_code` (`DISCOUNT_CODE`),
    INDEX `idx_discount_dates` (`START_AT`, `END_AT`)
);

-- Table: ORDER (renamed from ORDERS to avoid reserved word)
CREATE TABLE `ORDER` (
    `ORDER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `ORDER_CODE` VARCHAR(50) NOT NULL UNIQUE,
    `ORDER_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `CART_ID` BIGINT NOT NULL,
    `ORDER_STATE_ID` BIGINT NOT NULL,
    `DISCOUNT_ID` BIGINT,
    `TOTAL_AMOUNT` DECIMAL(15,2) NOT NULL,
    `ORDER_NOTE` TEXT,
    `ORDER_REMARK_EN` VARCHAR(256),
    `ORDER_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`),
    FOREIGN KEY (`CART_ID`) REFERENCES `CART`(`CART_ID`),
    FOREIGN KEY (`ORDER_STATE_ID`) REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`),
    FOREIGN KEY (`DISCOUNT_ID`) REFERENCES `DISCOUNT`(`DISCOUNT_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_order_code` (`ORDER_CODE`),
    INDEX `idx_order_slug` (`ORDER_SLUG`),
    INDEX `idx_order_user` (`USER_ID`),
    INDEX `idx_order_date` (`CREATED_DT`),
    INDEX `idx_order_seo_meta` (`SEO_META_ID`)
);

-- Table: ORDER_STATE_HISTORY
CREATE TABLE `ORDER_STATE_HISTORY` (
    `ORDER_STATE_HISTORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `ORDER_STATE_HISTORY_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `OLD_STATE_ID` BIGINT NOT NULL,
    `NEW_STATE_ID` BIGINT NOT NULL,
    `ORDER_STATE_HISTORY_NOTE` TEXT,
    `ORDER_STATE_HISTORY_REMARK_EN` VARCHAR(256),
    `ORDER_STATE_HISTORY_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`OLD_STATE_ID`) REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`),
    FOREIGN KEY (`NEW_STATE_ID`) REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_order_history_order` (`ORDER_ID`),
    INDEX `idx_order_history_slug` (`ORDER_STATE_HISTORY_SLUG`),
    INDEX `idx_order_history_seo_meta` (`SEO_META_ID`)
);

-- Table: ORDER_ITEM
CREATE TABLE `ORDER_ITEM` (
    `ORDER_ITEM_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `UNIT_PRICE` DECIMAL(15,2) NOT NULL,
    `ORDER_ITEM_QUANTITY` INT NOT NULL,
    `ORDER_ITEM_TOTAL_PRICE` DECIMAL(15,2) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`),
    INDEX `idx_order_item_order` (`ORDER_ID`),
    INDEX `idx_order_item_product` (`PRODUCT_ID`)
);

-- =============================================
-- PAYMENT SYSTEM TABLES
-- =============================================

-- Table: PAYMENT_METHOD
CREATE TABLE `PAYMENT_METHOD` (
    `PAYMENT_METHOD_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAYMENT_METHOD_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_METHOD_REMARK_EN` VARCHAR(256),
    `PAYMENT_METHOD_REMARK` VARCHAR(256) NOT NULL,
    `PAYMENT_METHOD_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_payment_method_name` (`PAYMENT_METHOD_NAME`)
);

-- Table: PAYMENT_STATE
CREATE TABLE `PAYMENT_STATE` (
    `PAYMENT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAYMENT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_STATE_REMARK_EN` VARCHAR(256),
    `PAYMENT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `PAYMENT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_payment_state_name` (`PAYMENT_STATE_NAME`)
);

-- Table: PAYMENT
CREATE TABLE `PAYMENT` (
    `PAYMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `PAYMENT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_METHOD_ID` BIGINT NOT NULL,
    `PAYMENT_STATE_ID` BIGINT NOT NULL,
    `AMOUNT` DECIMAL(15,2) NOT NULL,
    `TRANSACTION_ID` VARCHAR(100) NOT NULL,
    `PAYMENT_REMARK_EN` VARCHAR(256),
    `PAYMENT_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
    FOREIGN KEY (`PAYMENT_METHOD_ID`) REFERENCES `PAYMENT_METHOD`(`PAYMENT_METHOD_ID`),
    FOREIGN KEY (`PAYMENT_STATE_ID`) REFERENCES `PAYMENT_STATE`(`PAYMENT_STATE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_payment_order` (`ORDER_ID`),
    INDEX `idx_payment_slug` (`PAYMENT_SLUG`),
    INDEX `idx_payment_transaction` (`TRANSACTION_ID`),
    INDEX `idx_payment_seo_meta` (`SEO_META_ID`)
);

-- =============================================
-- SHIPPING SYSTEM TABLES
-- =============================================

-- Table: SHIPPING_FEE_TYPE
CREATE TABLE `SHIPPING_FEE_TYPE` (
    `SHIPPING_FEE_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPPING_FEE_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `SHIPPING_FEE_TYPE_REMARK_EN` VARCHAR(256),
    `SHIPPING_FEE_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPPING_FEE_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_shipping_fee_type_name` (`SHIPPING_FEE_TYPE_NAME`)
);

-- Table: SHIPPING_FEE
CREATE TABLE `SHIPPING_FEE` (
    `SHIPPING_FEE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPPING_FEE_TYPE_ID` BIGINT NOT NULL,
    `MIN_ORDER_PRICE` DECIMAL(15,2) NOT NULL,
    `MAX_ORDER_PRICE` DECIMAL(15,2) NOT NULL,
    `SHIPPING_FEE_VALUE` DECIMAL(15,2) NOT NULL,
    `SHIPPING_FEE_REMARK_EN` VARCHAR(256),
    `SHIPPING_FEE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPPING_FEE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SHIPPING_FEE_TYPE_ID`) REFERENCES `SHIPPING_FEE_TYPE`(`SHIPPING_FEE_TYPE_ID`),
    INDEX `idx_shipping_fee_price_range` (`MIN_ORDER_PRICE`, `MAX_ORDER_PRICE`)
);

-- Table: SHIPMENT_STATE
CREATE TABLE `SHIPMENT_STATE` (
    `SHIPMENT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPMENT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `SHIPMENT_STATE_REMARK_EN` VARCHAR(256),
    `SHIPMENT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPMENT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_shipment_state_name` (`SHIPMENT_STATE_NAME`)
);

-- Table: SHIPMENT
CREATE TABLE `SHIPMENT` (
    `SHIPMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `SHIPMENT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `SHIPPING_FEE_ID` BIGINT NOT NULL,
    `SHIPMENT_STATE_ID` BIGINT NOT NULL,
    `PHONE` VARCHAR(20) NOT NULL,
    `ADDRESS` VARCHAR(256) NOT NULL,
    `SHIPMENT_REMARK_EN` VARCHAR(256),
    `SHIPMENT_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
    FOREIGN KEY (`SHIPPING_FEE_ID`) REFERENCES `SHIPPING_FEE`(`SHIPPING_FEE_ID`),
    FOREIGN KEY (`SHIPMENT_STATE_ID`) REFERENCES `SHIPMENT_STATE`(`SHIPMENT_STATE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_shipment_order` (`ORDER_ID`),
    INDEX `idx_shipment_slug` (`SHIPMENT_SLUG`),
    INDEX `idx_shipment_seo_meta` (`SEO_META_ID`)
);

-- =============================================
-- CONTENT MANAGEMENT TABLES
-- =============================================

-- Table: BLOG_CATEGORY
CREATE TABLE `BLOG_CATEGORY` (
    `BLOG_CATEGORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_CATEGORY_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CATEGORY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CATEGORY_REMARK_EN` VARCHAR(256),
    `BLOG_CATEGORY_REMARK` VARCHAR(256) NOT NULL,
    `BLOG_CATEGORY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_category_slug` (`BLOG_CATEGORY_SLUG`),
    INDEX `idx_blog_category_seo_meta` (`SEO_META_ID`)
);

-- Table: BLOG_TYPE
CREATE TABLE `BLOG_TYPE` (
    `BLOG_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_TYPE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_TYPE_REMARK_EN` VARCHAR(256),
    `BLOG_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `BLOG_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_type_slug` (`BLOG_TYPE_SLUG`),
    INDEX `idx_blog_type_seo_meta` (`SEO_META_ID`)
);

-- Table: BLOG
CREATE TABLE `BLOG` (
    `BLOG_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_CATEGORY_ID` BIGINT NOT NULL,
    `BLOG_TYPE_ID` BIGINT NOT NULL,
    `BLOG_TITLE` VARCHAR(256) NOT NULL,
    `BLOG_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CONTENT` LONGTEXT NOT NULL,
    `BLOG_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `BLOG_REMARK_EN` VARCHAR(256),
    `BLOG_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`BLOG_CATEGORY_ID`) REFERENCES `BLOG_CATEGORY`(`BLOG_CATEGORY_ID`),
    FOREIGN KEY (`BLOG_TYPE_ID`) REFERENCES `BLOG_TYPE`(`BLOG_TYPE_ID`),
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_slug` (`BLOG_SLUG`),
    INDEX `idx_blog_title` (`BLOG_TITLE`),
    INDEX `idx_blog_seo_meta` (`SEO_META_ID`)
);

-- =============================================
-- CONFIGURATION TABLES
-- =============================================

-- Table: CONTACT
CREATE TABLE `CONTACT` (
    `CONTACT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CONTACT_NAME` VARCHAR(64) NOT NULL,
    `CONTACT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `CONTACT_ADDRESS` VARCHAR(256) NOT NULL,
    `CONTACT_EMAIL` VARCHAR(64) NOT NULL,
    `CONTACT_PHONE` VARCHAR(15) NOT NULL,
    `CONTACT_FANPAGE` VARCHAR(256),
    `CONTACT_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CONTACT_REMARK_EN` VARCHAR(256),
    `CONTACT_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_contact_email` (`CONTACT_EMAIL`),
    INDEX `idx_contact_slug` (`CONTACT_SLUG`),
    INDEX `idx_contact_seo_meta` (`SEO_META_ID`)
);

-- Table: POLICY
CREATE TABLE `POLICY` (
    `POLICY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `POLICY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `POLICY_SLUG` VARCHAR(64),
    `POLICY_VALUE` TEXT NOT NULL,
    `POLICY_REMARK_EN` VARCHAR(256),
    `POLICY_REMARK` VARCHAR(256) NOT NULL,
    `POLICY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_policy_name` (`POLICY_NAME`),
    INDEX `idx_policy_slug` (`POLICY_SLUG`)
);

-- Table: RESPONSE_CODE
CREATE TABLE `RESPONSE_CODE` (
    `RESPONSE_CODE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `RESPONSE_CODE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `RESPONSE_CODE_REMARK_EN` VARCHAR(256),
    `RESPONSE_CODE_REMARK` VARCHAR(256) NOT NULL,
    `RESPONSE_CODE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_response_code_name` (`RESPONSE_CODE_NAME`)
);

-- =============================================
-- INSERT INITIAL DATA
-- =============================================


-- Insert Policy Data
INSERT INTO `POLICY` (`POLICY_NAME`, `POLICY_SLUG`, `POLICY_VALUE`, `POLICY_REMARK_EN`, `POLICY_REMARK`, `POLICY_ENABLED`) VALUES
('FAVICON', 'favicon', 'favicon.ico', 'Favicon file name', 'Tên file favicon', TRUE),
('SOCIAL_IMAGE', 'social-image', 'social-image.jpg', 'Social image file name', 'Tên file ảnh mạng xã hội', TRUE),
('MENU_HEADER_TEXT_03', 'menu-header-text-03', 'Shops', 'Shops menu text', 'Text menu cửa hàng', TRUE),
('STORAGE_PATH', 'storage-path', '/storage', 'Storage path', 'Đường dẫn lưu trữ', TRUE),
('MENU_HEADER_TEXT_05', 'menu-header-text-05', 'Liên hệ', 'Contact menu text', 'Text menu liên hệ', TRUE),
('HERO_SECTION_TITLE', 'hero-section-title', 'Lorem Ipsum', 'Hero section main title', 'Tiêu đề chính của hero section', TRUE),
('HERO_SECTION_SUBTITLE', 'hero-section-subtitle', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus in libero risus semper habitant arcu eget.', 'Hero section subtitle', 'Phụ đề của hero section', TRUE),
('SECTION_TITLE', 'section-title', 'LOREM', 'General section title', 'Tiêu đề section chung', TRUE),
('SECTION_SUBTITLE', 'section-subtitle', 'LOREM IPSUM DOLOR SIT AMET.', 'General section subtitle', 'Phụ đề section chung', TRUE),
('SECTION_IMAGE_01', 'section-image-01', 'pho-co-hoi-an.jpg', 'First section image filename', 'Tên file ảnh section thứ nhất', TRUE),
('SECTION_IMAGE_02', 'section-image-02', 'nui-phu-si.jpg', 'Second section image filename', 'Tên file ảnh section thứ hai', TRUE),
('SECTION_DESCRIPTION_01', 'section-description-01', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus in libero risus 01...', 'First section description', 'Mô tả section thứ nhất', TRUE),
('SECTION_DESCRIPTION_02', 'section-description-02', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus in libero risus 02...', 'Second section description', 'Mô tả section thứ hai', TRUE),
('WEBSITE_LOGO_ALT_TEXT', 'website-logo-alt-text', 'Maison Art', 'Website logo alt text', 'Alt text cho logo website', TRUE),
('FOOTER_ABOUT_TEXT', 'footer-about-text', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean commodo ligula eget dolor.', 'Footer about text', 'Text giới thiệu ở footer', TRUE),
('FOOTER_COPYRIGHT_TEXT', 'footer-copyright-text', '© 2025 Palette & Co. Giữ toàn quyền.', 'Footer copyright text', 'Text bản quyền ở footer', TRUE);

-- Insert SEO Meta Data
INSERT INTO `SEO_META` (`SEO_META_TITLE`, `SEO_META_DESCRIPTION`, `SEO_META_KEYWORDS`, `SEO_META_INDEX`, `SEO_META_FOLLOW`, `SEO_META_ENABLED`) VALUES
-- SEO for Image Categories
('Scenery Images - Phong Cảnh Thiên Nhiên', 'Discover beautiful landscape and nature images for decoration. High quality scenery pictures for your home and office.', 'scenery, landscape, nature, images, decoration, phong cảnh, thiên nhiên', TRUE, TRUE, TRUE),
('Art Images - Hình Ảnh Nghệ Thuật', 'Explore artistic images and creative artworks. Professional art collection for interior decoration and design.', 'art, artistic, images, artwork, creative, nghệ thuật, sáng tạo', TRUE, TRUE, TRUE),
('Decoration Images - Hình Ảnh Trang Trí', 'Beautiful decoration images for interior design. Transform your space with stunning decorative pictures.', 'decoration, interior, design, decorative, pictures, trang trí, nội thất', TRUE, TRUE, TRUE),
('Portrait Images - Hình Ảnh Chân Dung', 'Professional portrait images and photography. Capture memorable moments with high-quality portraits.', 'portrait, photography, professional, memorable, chân dung, nhiếp ảnh', TRUE, TRUE, TRUE),
('Religious Images - Hình Ảnh Tôn Giáo', 'Spiritual and religious images for meditation and worship. Sacred art for your spiritual space.', 'religious, spiritual, meditation, worship, sacred, tôn giáo, tâm linh', TRUE, TRUE, TRUE),
('Avatar Images - Ảnh Đại Diện', 'User avatar images and profile pictures. Personalize your online presence with unique avatars.', 'avatar, profile, pictures, user, online, đại diện, cá nhân', TRUE, TRUE, TRUE),
('Website Banners - Banner Trang Web', 'Professional website banners and headers. Eye-catching designs for your digital presence.', 'banner, website, header, professional, digital, trang web, thiết kế', TRUE, TRUE, TRUE),
-- SEO for Image Formats
('JPEG Format - Định Dạng JPEG', 'High-quality JPEG image format for photography and digital art. Optimized compression for web and print.', 'jpeg, format, photography, digital, compression, định dạng, chất lượng', TRUE, TRUE, TRUE),
('PNG Format - Định Dạng PNG', 'PNG image format with transparency support. Perfect for logos, icons, and graphic design elements.', 'png, format, transparency, logos, icons, graphic, định dạng, trong suốt', TRUE, TRUE, TRUE),
('WebP Format - Định Dạng WebP', 'Modern WebP image format with superior compression. Faster loading times for web applications.', 'webp, format, compression, modern, web, loading, định dạng, nén', TRUE, TRUE, TRUE),
('SVG Format - Định Dạng SVG', 'Scalable Vector Graphics format. Perfect for logos and illustrations that need to scale perfectly.', 'svg, vector, scalable, graphics, logos, illustrations, định dạng, vector', TRUE, TRUE, TRUE),
-- SEO for Product Categories
('Tranh Treo Tường - Wall Paintings', 'Bộ sưu tập tranh treo tường đẹp cho không gian sống. Trang trí nội thất với nghệ thuật chất lượng cao.', 'tranh treo tường, wall paintings, decoration, interior, art, trang trí, nội thất', TRUE, TRUE, TRUE),
('Dụng Cụ Vẽ - Drawing Tools', 'Dụng cụ vẽ chuyên nghiệp cho nghệ sĩ và người yêu nghệ thuật. Chất lượng cao, giá tốt nhất.', 'dụng cụ vẽ, drawing tools, art supplies, professional, nghệ thuật, chuyên nghiệp', TRUE, TRUE, TRUE),
('Decor Nội Thất - Interior Decoration', 'Sản phẩm decor nội thất hiện đại và sang trọng. Biến đổi không gian sống của bạn.', 'decor nội thất, interior decoration, modern, luxury, trang trí, hiện đại', TRUE, TRUE, TRUE),
('Khung Tranh - Picture Frames', 'Khung tranh chất lượng cao, đa dạng mẫu mã. Bảo vệ và làm đẹp cho tác phẩm nghệ thuật của bạn.', 'khung tranh, picture frames, quality, protect, artwork, chất lượng, bảo vệ', TRUE, TRUE, TRUE),
-- SEO for Product Types
('Image Products - Sản Phẩm Hình Ảnh', 'Sản phẩm hình ảnh chất lượng cao cho trang trí và nghệ thuật. Đa dạng chủ đề và phong cách.', 'image products, high quality, decoration, art, diverse, chất lượng cao, đa dạng', TRUE, TRUE, TRUE),
('Decor Products - Sản Phẩm Trang Trí', 'Sản phẩm trang trí nội thất độc đáo và sáng tạo. Làm đẹp không gian sống của bạn.', 'decor products, interior, unique, creative, beautiful, trang trí, độc đáo', TRUE, TRUE, TRUE),
('Tools Products - Sản Phẩm Dụng Cụ', 'Dụng cụ và thiết bị vẽ chuyên nghiệp. Hỗ trợ tối đa cho quá trình sáng tạo nghệ thuật.', 'tools, equipment, professional, art, creative, support, dụng cụ, chuyên nghiệp', TRUE, TRUE, TRUE),
-- SEO for Blog Categories
('Tin Tức Nghệ Thuật - Art News', 'Cập nhật tin tức mới nhất về nghệ thuật và trang trí. Khám phá xu hướng và sự kiện nghệ thuật.', 'tin tức, art news, trends, events, nghệ thuật, xu hướng, sự kiện', TRUE, TRUE, TRUE),
('Hướng Dẫn Nghệ Thuật - Art Tutorials', 'Hướng dẫn chi tiết về kỹ thuật vẽ và trang trí. Học hỏi từ các chuyên gia nghệ thuật.', 'hướng dẫn, tutorials, techniques, expert, learn, kỹ thuật, chuyên gia', TRUE, TRUE, TRUE),
('Sự Kiện Nghệ Thuật - Art Events', 'Thông tin về các sự kiện, triển lãm và hoạt động nghệ thuật. Tham gia cộng đồng yêu nghệ thuật.', 'sự kiện, events, exhibition, community, art, triển lãm, cộng đồng', TRUE, TRUE, TRUE),
-- SEO for Blog Types
('Bài Viết Nghệ Thuật - Art Articles', 'Bài viết chuyên sâu về nghệ thuật và trang trí. Kiến thức và kinh nghiệm từ các chuyên gia.', 'bài viết, articles, expert, knowledge, experience, chuyên sâu, kiến thức', TRUE, TRUE, TRUE),
('Video Nghệ Thuật - Art Videos', 'Video hướng dẫn và giải trí về nghệ thuật. Học hỏi qua hình ảnh trực quan và sinh động.', 'video, tutorials, visual, learn, entertainment, trực quan, sinh động', TRUE, TRUE, TRUE),
('Thư Viện Hình Ảnh - Image Gallery', 'Thư viện hình ảnh nghệ thuật phong phú và đa dạng. Khám phá và lưu giữ những tác phẩm đẹp.', 'thư viện, gallery, diverse, artwork, beautiful, phong phú, tác phẩm', TRUE, TRUE, TRUE);

-- Insert User Providers
INSERT INTO `USER_PROVIDER` (`USER_PROVIDER_NAME`, `USER_PROVIDER_REMARK_EN`, `USER_PROVIDER_REMARK`, `USER_PROVIDER_ENABLED`) VALUES
('LOCAL', 'Local registration', 'Đăng ký trực tiếp trên hệ thống', TRUE),
('GOOGLE', 'Google OAuth', 'Đăng nhập qua Google', TRUE),
('FACEBOOK', 'Facebook OAuth', 'Đăng nhập qua Facebook', TRUE),
('GITHUB', 'GitHub OAuth', 'Đăng nhập qua GitHub', TRUE);

-- Insert User Roles
-- Website supports only 2 roles: ADMIN and CUSTOMER
INSERT INTO `USER_ROLE` (`USER_ROLE_NAME`, `USER_ROLE_REMARK_EN`, `USER_ROLE_REMARK`, `USER_ROLE_ENABLED`) VALUES
('CUSTOMER', 'Customer', 'Khách hàng', TRUE),
('ADMIN', 'System Administrator', 'Quản trị viên hệ thống', TRUE);

-- Insert Image Categories
-- IMAGE_CATEGORY sample data removed as per requirements

-- Insert Image Formats
-- IMAGE_FORMAT table removed as per requirements

-- Insert Product Types
INSERT INTO `PRODUCT_TYPE` (`PRODUCT_TYPE_SLUG`, `PRODUCT_TYPE_NAME`, `PRODUCT_TYPE_REMARK_EN`, `PRODUCT_TYPE_REMARK`, `PRODUCT_TYPE_ENABLED`, `PRODUCT_TYPE_DISPLAY`, `SEO_META_ID`, `PRODUCT_TYPE_IMAGE_NAME`) VALUES
('image', 'IMAGE', 'Image products', 'Các sản phẩm hình ảnh', TRUE, TRUE, 16, 'image_type.png'),
('decor', 'DECOR', 'Decoration products', 'Các sản phẩm trang trí', TRUE, TRUE, 17, NULL),
('tools', 'TOOLS', 'Drawing tools and equipment', 'Dụng cụ và thiết bị vẽ', TRUE, TRUE, 18, NULL);

-- Insert Product Categories
INSERT INTO `PRODUCT_CATEGORY` (`PRODUCT_CATEGORY_SLUG`, `PRODUCT_CATEGORY_NAME`, `PRODUCT_CATEGORY_REMARK_EN`, `PRODUCT_CATEGORY_REMARK`, `PRODUCT_CATEGORY_ENABLED`, `PRODUCT_CATEGORY_DISPLAY`, `SEO_META_ID`, `PRODUCT_TYPE_ID`, `PRODUCT_CATEGORY_PARENT_ID`, `PRODUCT_CATEGORY_IMAGE_NAME`) VALUES
('tranh', 'Tranh', 'All paintings', 'Tất cả các loại tranh', TRUE, TRUE, 12, 1, NULL, 'tranh_main.png'),
('tranh-treo-tuong', 'Tranh treo tường', 'Wall paintings', 'Các loại tranh dùng để trang trí treo tường', TRUE, TRUE, 12, 1, 1, NULL),
('dung-cu-ve', 'Dụng cụ vẽ', 'Drawing tools', 'Các dụng cụ, thiết bị dùng để vẽ tranh', TRUE, TRUE, 13, 3, NULL, NULL),
('decor-noi-that', 'Decor nội thất', 'Interior decoration', 'Các sản phẩm trang trí nội thất', TRUE, TRUE, 14, 2, NULL, NULL),
('khung-tranh', 'Khung tranh', 'Picture frames', 'Các loại khung để đóng tranh', TRUE, TRUE, 15, 1, 1, NULL);

-- Insert Product States
INSERT INTO `PRODUCT_STATE` (`PRODUCT_STATE_NAME`, `PRODUCT_STATE_ENABLED`, `PRODUCT_STATE_REMARK_EN`, `PRODUCT_STATE_REMARK`) VALUES
('ACTIVE', TRUE, 'Product is active', 'Sản phẩm đang hoạt động'),
('INACTIVE', TRUE, 'Product is inactive', 'Sản phẩm tạm ngưng'),
('OUT_OF_STOCK', TRUE, 'Product is out of stock', 'Sản phẩm hết hàng'),
('DISCONTINUED', TRUE, 'Product is discontinued', 'Sản phẩm ngưng kinh doanh');

-- Insert Product Attributes
INSERT INTO `PRODUCT_ATTR` (`PRODUCT_ATTR_NAME`, `PRODUCT_ATTR_ENABLED`, `PRODUCT_ATTR_REMARK_EN`, `PRODUCT_ATTR_REMARK`) VALUES
('SIZE', TRUE, 'Product size', 'Kích thước sản phẩm'),
('COLOR', TRUE, 'Product color', 'Màu sắc sản phẩm'),
('MATERIAL', TRUE, 'Product material', 'Chất liệu sản phẩm'),
('BRAND', TRUE, 'Product brand', 'Thương hiệu sản phẩm'),
('WEIGHT', TRUE, 'Product weight', 'Trọng lượng sản phẩm');

-- Insert Cart States
INSERT INTO `CART_STATE` (`CART_STATE_NAME`, `CART_STATE_REMARK_EN`, `CART_STATE_REMARK`, `CART_STATE_ENABLED`) VALUES
('ACTIVE', 'Active cart in use', 'Giỏ hàng đang hoạt động', TRUE),
('CHECKED_OUT', 'All items have been ordered', 'Đã đặt hàng toàn bộ sản phẩm', TRUE),
('CHECKED_OUT_PART', 'Some items have been ordered', 'Đã đặt hàng một phần sản phẩm', TRUE),
('ABANDONED', 'Cart has been abandoned or expired', 'Giỏ hàng đã hết hạn hoặc bị bỏ rơi', TRUE);

-- Insert Cart Item States
INSERT INTO `CART_ITEM_STATE` (`CART_ITEM_STATE_NAME`, `CART_ITEM_STATE_REMARK_EN`, `CART_ITEM_STATE_REMARK`, `CART_ITEM_STATE_ENABLED`) VALUES
('ACTIVE', 'Active cart item', 'Sản phẩm trong giỏ hàng đang hoạt động', TRUE),
('ORDERED', 'Cart item ordered', 'Sản phẩm đã được đặt hàng', TRUE);

-- Insert Order States
INSERT INTO `ORDER_STATE` (`ORDER_STATE_NAME`, `ORDER_STATE_REMARK_EN`, `ORDER_STATE_REMARK`, `ORDER_STATE_ENABLED`) VALUES
('PENDING', 'Order is pending', 'Đơn hàng đang chờ xử lý', TRUE),
('CONFIRMED', 'Order is confirmed', 'Đơn hàng đã xác nhận', TRUE),
('PROCESSING', 'Order is being processed', 'Đơn hàng đang xử lý', TRUE),
('SHIPPED', 'Order has been shipped', 'Đơn hàng đã giao cho vận chuyển', TRUE),
('DELIVERED', 'Order has been delivered', 'Đơn hàng đã giao thành công', TRUE),
('CANCELLED', 'Order has been cancelled', 'Đơn hàng đã hủy', TRUE),
('RETURNED', 'Order has been returned', 'Đơn hàng đã trả lại', TRUE);

-- Insert Payment Methods
INSERT INTO `PAYMENT_METHOD` (`PAYMENT_METHOD_NAME`, `PAYMENT_METHOD_REMARK_EN`, `PAYMENT_METHOD_REMARK`, `PAYMENT_METHOD_ENABLED`) VALUES
('COD', 'Cash on Delivery', 'Thanh toán khi nhận hàng', TRUE),
('BANK_TRANSFER', 'Bank Transfer', 'Chuyển khoản ngân hàng', TRUE),
('MOMO', 'MoMo E-wallet', 'Ví điện tử MoMo', TRUE),
('ZALOPAY', 'ZaloPay E-wallet', 'Ví điện tử ZaloPay', TRUE),
('VNPAY', 'VNPay Gateway', 'Cổng thanh toán VNPay', TRUE);

-- Insert Payment States
INSERT INTO `PAYMENT_STATE` (`PAYMENT_STATE_NAME`, `PAYMENT_STATE_REMARK_EN`, `PAYMENT_STATE_REMARK`, `PAYMENT_STATE_ENABLED`) VALUES
('PENDING', 'Payment is pending', 'Thanh toán đang chờ xử lý', TRUE),
('COMPLETED', 'Payment completed', 'Thanh toán thành công', TRUE),
('FAILED', 'Payment failed', 'Thanh toán thất bại', TRUE),
('REFUNDED', 'Payment refunded', 'Thanh toán đã hoàn lại', TRUE);

-- Insert Shipment States
INSERT INTO `SHIPMENT_STATE` (`SHIPMENT_STATE_NAME`, `SHIPMENT_STATE_REMARK_EN`, `SHIPMENT_STATE_REMARK`, `SHIPMENT_STATE_ENABLED`) VALUES
('PREPARING', 'Package is being prepared', 'Đang chuẩn bị hàng', TRUE),
('SHIPPED', 'Package has been shipped', 'Đã giao cho đơn vị vận chuyển', TRUE),
('IN_TRANSIT', 'Package is in transit', 'Đang vận chuyển', TRUE),
('DELIVERED', 'Package delivered', 'Đã giao hàng thành công', TRUE),
('FAILED_DELIVERY', 'Delivery failed', 'Giao hàng thất bại', TRUE);

-- Insert Shipping Fee Types
INSERT INTO `SHIPPING_FEE_TYPE` (`SHIPPING_FEE_TYPE_NAME`, `SHIPPING_FEE_TYPE_REMARK_EN`, `SHIPPING_FEE_TYPE_REMARK`, `SHIPPING_FEE_TYPE_ENABLED`) VALUES
('PERCENTAGE', 'Percentage-based shipping fee', 'Phí vận chuyển tính theo phần trăm', TRUE),
('FIXED_AMOUNT', 'Fixed amount shipping fee', 'Phí vận chuyển số tiền cố định', TRUE),
('FREE_SHIPPING', 'Free shipping', 'Miễn phí vận chuyển', TRUE);

-- Insert Discount Types
INSERT INTO `DISCOUNT_TYPE` (`DISCOUNT_TYPE_NAME`, `DISCOUNT_TYPE_REMARK_EN`, `DISCOUNT_TYPE_REMARK`, `DISCOUNT_TYPE_ENABLED`) VALUES
('PERCENTAGE', 'Percentage discount', 'Giảm giá theo phần trăm', TRUE),
('FIXED_AMOUNT', 'Fixed amount discount', 'Giảm giá số tiền cố định', TRUE);

-- Insert Blog Categories
INSERT INTO `BLOG_CATEGORY` (`BLOG_CATEGORY_SLUG`, `BLOG_CATEGORY_NAME`, `BLOG_CATEGORY_REMARK_EN`, `BLOG_CATEGORY_REMARK`, `BLOG_CATEGORY_ENABLED`, `SEO_META_ID`) VALUES
('tin-tuc', 'Tin tức', 'News', 'Tin tức về nghệ thuật và trang trí', TRUE, 19),
('huong-dan', 'Hướng dẫn', 'Tutorials', 'Hướng dẫn vẽ và trang trí', TRUE, 20),
('su-kien', 'Sự kiện', 'Events', 'Các sự kiện nghệ thuật', TRUE, 21);

-- Insert Blog Types
INSERT INTO `BLOG_TYPE` (`BLOG_TYPE_SLUG`, `BLOG_TYPE_NAME`, `BLOG_TYPE_REMARK_EN`, `BLOG_TYPE_REMARK`, `BLOG_TYPE_ENABLED`, `SEO_META_ID`) VALUES
('bai-viet', 'Bài viết', 'Article', 'Bài viết thông thường', TRUE, 22),
('video', 'Video', 'Video content', 'Nội dung video', TRUE, 23),
('hinh-anh', 'Hình ảnh', 'Image gallery', 'Thư viện hình ảnh', TRUE, 24);

-- =============================================
-- INSERT SEO_META DATA FOR CONTENT INSTANCES
-- =============================================

-- Additional SEO Meta Data for content instances (IDs 25-70)
INSERT INTO `SEO_META` (`SEO_META_TITLE`, `SEO_META_DESCRIPTION`, `SEO_META_KEYWORDS`, `SEO_META_INDEX`, `SEO_META_FOLLOW`, `SEO_META_CANONICAL_URL`, `SEO_META_IMAGE_NAME`, `SEO_META_SCHEMA_TYPE`, `SEO_META_CUSTOM_JSON`, `SEO_META_ENABLED`) VALUES

-- SEO for specific Images (IDs 25-34)
('Tranh Phong Cảnh Hoàng Hôn Biển - Sunset Seascape Painting', 'Khám phá vẻ đẹp hoàng hôn trên biển với tranh phong cảnh tuyệt đẹp này. Chất liệu canvas cao cấp, màu sắc sống động, thích hợp trang trí phòng khách và phòng ngủ.', 'tranh hoàng hôn, phong cảnh biển, sunset painting, tranh trang trí, canvas art', TRUE, TRUE, '/images/sunset-seascape-001', '1A2B3C4D5E6F789012345678901234567890ABCD', 'ImageObject', '{"@context": "https://schema.org", "@type": "ImageObject", "name": "Sunset Seascape Painting", "contentUrl": "/images/sunset-seascape-001.jpg", "thumbnailUrl": "/images/thumbs/sunset-seascape-001.jpg", "width": 1920, "height": 1080, "encodingFormat": "image/jpeg"}', TRUE),
('Tranh Núi Non Hùng Vĩ - Mountain Landscape Art', 'Cảnh quan núi non hùng vĩ trong sương mù, thể hiện sự uy nghiêm và bình yên của thiên nhiên. Tranh phong cảnh cao cấp cho không gian sống hiện đại.', 'tranh núi non, mountain landscape, phong cảnh núi, thiên nhiên, nature art', TRUE, TRUE, '/images/mountain-landscape-002', '2B3C4D5E6F789012345678901234567890ABCDE1', 'ImageObject', '{"@context": "https://schema.org", "@type": "ImageObject", "name": "Mountain Landscape", "contentUrl": "/images/mountain-landscape-002.jpg", "width": 1920, "height": 1200}', TRUE),
('Nghệ Thuật Trừu Tượng Hiện Đại - Modern Abstract Art', 'Tác phẩm nghệ thuật trừu tượng với màu sắc và hình khối độc đáo. Phong cách hiện đại, tạo điểm nhấn nghệ thuật cho không gian sống và văn phòng.', 'abstract art, nghệ thuật trừu tượng, modern art, tranh hiện đại', TRUE, TRUE, '/images/modern-abstract-001', '3C4D5E6F789012345678901234567890ABCDEF12', 'VisualArtwork', '{"@context": "https://schema.org", "@type": "VisualArtwork", "name": "Modern Abstract Art", "artform": "painting", "artMedium": "canvas"}', TRUE),
('Tranh Trang Trí Nội Thất - Home Decoration Art', 'Bộ sưu tập tranh trang trí nội thất cao cấp, phù hợp với mọi phong cách từ cổ điển đến hiện đại. Tạo không gian sống đẳng cấp và tinh tế.', 'trang trí nội thất, home decoration, interior art, decor painting', TRUE, TRUE, '/images/home-decoration-001', '5E6F789012345678901234567890ABCDEF1234', 'ImageObject', '{"@context": "https://schema.org", "@type": "ImageObject", "name": "Home Decoration Art"}', TRUE),
('Tranh Chân Dung Nghệ Thuật - Portrait Art Collection', 'Bộ sưu tập tranh chân dung nghệ thuật với kỹ thuật vẽ tinh xảo. Thể hiện cảm xúc và cá tính qua từng nét vẽ, phù hợp trang trí phòng riêng.', 'tranh chân dung, portrait art, nghệ thuật chân dung, portrait painting', TRUE, TRUE, '/images/portrait-art-001', '789012345678901234567890ABCDEF123456', 'VisualArtwork', '{"@context": "https://schema.org", "@type": "VisualArtwork", "artform": "portrait"}', TRUE),
('Tranh Tôn Giáo Tâm Linh - Religious Spiritual Art', 'Tranh tôn giáo với ý nghĩa tâm linh sâu sắc, mang đến sự bình an và may mắn. Thích hợp cho không gian thờ cúng và tĩnh tâm.', 'tranh tôn giáo, religious art, tâm linh, spiritual painting, phật giáo', TRUE, TRUE, '/images/religious-art-001', '9012345678901234567890ABCDEF12345678', 'VisualArtwork', '{"@context": "https://schema.org", "@type": "VisualArtwork", "about": "Religious themes"}', TRUE),
('Avatar Nghệ Thuật Cá Nhân - Personal Art Avatar', 'Hình đại diện nghệ thuật với thiết kế độc đáo và cá tính. Thể hiện phong cách riêng biệt trong thế giới số và mạng xã hội.', 'avatar nghệ thuật, art avatar, personal avatar, digital art', FALSE, FALSE, '/images/personal-avatar-001', '12345678901234567890ABCDEF123456789A', 'ImageObject', '{"@context": "https://schema.org", "@type": "ImageObject", "represents": "Person"}', FALSE),
('Banner Trang Chủ Nghệ Thuật - Art Homepage Banner', 'Banner trang chủ với thiết kế nghệ thuật chuyên nghiệp, giới thiệu bộ sưu tập tranh và sản phẩm trang trí đặc sắc của gallery.', 'banner homepage, art banner, website design, gallery banner', TRUE, TRUE, '/banners/homepage-art-001', '345678901234567890ABCDEF123456789ABC', 'ImageObject', '{"@context": "https://schema.org", "@type": "ImageObject", "name": "Art Gallery Homepage Banner"}', TRUE),
('Banner Khuyến Mãi Nghệ Thuật - Art Sale Promotion Banner', 'Banner khuyến mãi với thiết kế bắt mắt, quảng bá các chương trình giảm giá và ưu đãi đặc biệt cho sản phẩm nghệ thuật.', 'banner sale, promotion banner, art sale, discount banner', TRUE, TRUE, '/banners/art-sale-002', '45678901234567890ABCDEF123456789ABCD', 'PromotionalOffer', '{"@context": "https://schema.org", "@type": "PromotionalOffer", "name": "Art Sale Banner"}', TRUE),
('Tranh Rừng Thiên Nhiên - Nature Forest Painting', 'Cảnh rừng thiên nhiên hoang dã với màu xanh tươi mát, mang đến cảm giác thư giãn và gần gũi với tự nhiên cho không gian sống.', 'tranh rừng, nature forest, thiên nhiên, forest painting, landscape', TRUE, TRUE, '/images/nature-forest-003', '5678901234567890ABCDEF123456789ABCDE', 'VisualArtwork', '{"@context": "https://schema.org", "@type": "VisualArtwork", "depicts": "Forest landscape"}', TRUE),

-- SEO for specific Products (IDs 35-44)
('Mua Tranh Phong Cảnh Hoàng Hôn Biển 40x60cm - 450.000đ', 'Mua tranh phong cảnh hoàng hôn trên biển chính hãng, chất liệu canvas cao cấp, in UV bền màu. Kích thước 40x60cm, bảo hành 2 năm, giao hàng toàn quốc.', 'mua tranh phong cảnh, tranh hoàng hôn giá rẻ, tranh canvas 40x60, tranh trang trí phòng khách', TRUE, TRUE, '/products/sunset-seascape-painting-40x60', '1A2B3C4D5E6F789012345678901234567890ABCD', 'Product', '{"@context": "https://schema.org", "@type": "Product", "name": "Sunset Seascape Painting", "price": "450000", "priceCurrency": "VND", "availability": "InStock"}', TRUE),
('Tranh Núi Non Hùng Vĩ Canvas 50x70cm - Giá Tốt', 'Tranh núi non hùng vĩ chất liệu canvas cao cấp, kích thước 50x70cm. Phù hợp trang trí phòng khách, văn phòng. Màu sắc sống động, bền đẹp theo thời gian.', 'tranh núi non, mountain painting 50x70, tranh canvas núi, trang trí văn phòng', TRUE, TRUE, '/products/mountain-landscape-50x70', '2B3C4D5E6F789012345678901234567890ABCDE1', 'Product', '{"@context": "https://schema.org", "@type": "Product", "name": "Mountain Landscape Canvas", "material": "Canvas"}', TRUE),
('Tranh Trừu Tượng Hiện Đại 60x80cm Cho Phòng Khách', 'Tranh nghệ thuật trừu tượng hiện đại kích thước 60x80cm, thiết kế độc đáo tạo điểm nhấn cho phòng khách. Phong cách contemporary, chất lượng museum.', 'tranh trừu tượng phòng khách, abstract art 60x80, tranh hiện đại, contemporary art', TRUE, TRUE, '/products/modern-abstract-60x80', '3C4D5E6F789012345678901234567890ABCDEF12', 'Product', '{"@context": "https://schema.org", "@type": "Product", "category": "Abstract Art", "dimensions": "60x80cm"}', TRUE),
('Bộ Cọ Vẽ Chuyên Nghiệp 24 Cây - Dụng Cụ Họa Sĩ', 'Bộ cọ vẽ chuyên nghiệp gồm 24 cây cọ đa dạng: cọ tròn, dẹt, quạt. Lông tự nhiên và synthetic chất lượng cao, phù hợp acrylic, oil, watercolor.', 'bộ cọ vẽ 24 cây, cọ vẽ chuyên nghiệp, dụng cụ họa sĩ, art brush set', TRUE, TRUE, '/products/professional-brush-set-24pcs', '5E6F789012345678901234567890ABCDEF1234', 'Product', '{"@context": "https://schema.org", "@type": "Product", "name": "Professional Brush Set", "numberOfItems": 24}', TRUE),
('Đèn LED Trang Trí Phòng Khách Hiện Đại - Tiết Kiệm Điện', 'Đèn LED trang trí với thiết kế hiện đại, ánh sáng ấm có thể điều chỉnh độ sáng. Tiết kiệm điện, tuổi thọ cao, phù hợp phòng khách và phòng ngủ.', 'đèn led trang trí, đèn phòng khách hiện đại, led lighting, home decor lamp', TRUE, TRUE, '/products/modern-led-decoration-light', '6F789012345678901234567890ABCDEF12345', 'Product', '{"@context": "https://schema.org", "@type": "Product", "energyEfficiencyRating": "A++", "category": "LED Lighting"}', TRUE),
('Khung Tranh Gỗ Sồi 40x60cm - Chất Lượng Cao Cấp', 'Khung tranh gỗ sồi tự nhiên cao cấp, kích thước 40x60cm, gia công tỉ mỉ. Chống ẩm mối mọt, có kính bảo vệ, phù hợp đóng tranh nghệ thuật.', 'khung tranh gỗ sồi, picture frame 40x60, khung tranh cao cấp, oak frame', TRUE, TRUE, '/products/oak-picture-frame-40x60', 'A1B2C3D4E5F6789012345678901234567890ABCD', 'Product', '{"@context": "https://schema.org", "@type": "Product", "material": "Oak wood", "dimensions": "40x60cm"}', TRUE),
('Tượng Trang Trí Ceramic Nghệ Thuật - Decor Cao Cấp', 'Tượng trang trí bằng ceramic với thiết kế nghệ thuật tinh tế, cao 25cm. Màu sắc hài hòa, phù hợp để bàn làm việc, kệ sách, tạo điểm nhấn decor.', 'tượng ceramic trang trí, art sculpture, ceramic decor, home decoration', TRUE, TRUE, '/products/ceramic-art-sculpture', 'B2C3D4E5F6789012345678901234567890ABCDE', 'Product', '{"@context": "https://schema.org", "@type": "Product", "material": "Ceramic", "height": "25cm"}', TRUE),
('Màu Acrylic Cao Cấp Bộ 12 Tuýp - Họa Cụ Chuyên Nghiệp', 'Bộ màu acrylic cao cấp 12 tuýp x 20ml, màu sắc tươi sáng không phai. Khô nhanh, độ che phủ tốt, phù hợp cả người mới học và họa sĩ chuyên nghiệp.', 'màu acrylic 12 tuýp, acrylic paint set, màu vẽ cao cấp, art supplies', TRUE, TRUE, '/products/premium-acrylic-paint-set-12', 'C3D4E5F6789012345678901234567890ABCDEF', 'Product', '{"@context": "https://schema.org", "@type": "Product", "brand": "Premium Art", "numberOfItems": 12}', TRUE),
('Giấy Canvas Cotton A3 Chuyên Dụng Vẽ Tranh - 20 Tờ', 'Giấy canvas 100% cotton chất lượng cao, kích thước A3, bề mặt texture tự nhiên. Thấm màu tốt, phù hợp vẽ acrylic và oil. Gói 20 tờ giá ưu đãi.', 'giấy canvas A3, cotton canvas paper, giấy vẽ tranh chuyên dụng, art paper', TRUE, TRUE, '/products/cotton-canvas-paper-a3-20sheets', 'D4E5F6789012345678901234567890ABCDEF12', 'Product', '{"@context": "https://schema.org", "@type": "Product", "material": "100% Cotton", "size": "A3"}', TRUE),
('Tranh Chân Dung Cổ Điển 30x40cm - Nghệ Thuật Châu Âu', 'Tranh chân dung phong cách cổ điển châu Âu với kỹ thuật vẽ tinh tế. Thể hiện vẻ đẹp dịu dàng, kích thước 30x40cm phù hợp trang trí phòng ngủ.', 'tranh chân dung cổ điển, classical portrait, european art, vintage painting', TRUE, TRUE, '/products/classical-portrait-30x40', 'E5F6789012345678901234567890ABCDEF123', 'Product', '{"@context": "https://schema.org", "@type": "VisualArtwork", "artworkSurface": "canvas", "artform": "portrait"}', TRUE),

-- SEO for Carts (IDs 45-49)
('Giỏ Hàng Tranh Nghệ Thuật - Art Shopping Cart', 'Giỏ hàng chứa các sản phẩm tranh nghệ thuật và đồ trang trí đã chọn. Xem lại đơn hàng, tính phí vận chuyển và áp dụng mã giảm giá trước khi thanh toán.', 'giỏ hàng, shopping cart, mua tranh online, art shopping', FALSE, FALSE, '/cart/art-products', NULL, 'ShoppingCart', '{"@context": "https://schema.org", "@type": "ShoppingCart", "hasOfferCatalog": "Art Products"}', TRUE),
('Giỏ Hàng Dụng Cụ Vẽ - Art Supplies Cart', 'Các dụng cụ vẽ và nghệ thuật trong giỏ hàng. Cọ vẽ, màu acrylic, giấy canvas và phụ kiện họa sĩ với giá ưu đãi đặc biệt.', 'giỏ hàng dụng cụ vẽ, art supplies cart, mua cọ vẽ, họa cụ', FALSE, FALSE, '/cart/art-supplies', NULL, 'ShoppingCart', '{"@context": "https://schema.org", "@type": "ShoppingCart", "category": "Art Supplies"}', FALSE),
('Giỏ Hàng Trang Trí Nội Thất - Home Decor Cart', 'Sản phẩm trang trí nội thất trong giỏ hàng: đèn LED, tượng ceramic, khung tranh. Hoàn tất đơn hàng để nhận ưu đãi giao hàng miễn phí.', 'giỏ hàng decor, home decoration cart, trang trí nội thất, interior decor', FALSE, FALSE, '/cart/home-decor', NULL, 'ShoppingCart', '{"@context": "https://schema.org", "@type": "ShoppingCart", "category": "Home Decor"}', FALSE),
('Giỏ Hàng Khung Tranh - Picture Frames Cart', 'Các loại khung tranh cao cấp trong giỏ hàng: khung gỗ sồi, khung nhôm hiện đại. Bảo vệ và làm đẹp cho tác phẩm nghệ thuật của bạn.', 'giỏ hàng khung tranh, picture frames cart, khung tranh gỗ, frame shopping', FALSE, FALSE, '/cart/picture-frames', NULL, 'ShoppingCart', '{"@context": "https://schema.org", "@type": "ShoppingCart", "category": "Picture Frames"}', FALSE),
('Giỏ Hàng Hỗn Hợp - Mixed Art Products Cart', 'Giỏ hàng chứa đa dạng sản phẩm nghệ thuật: tranh, dụng cụ vẽ, decor nội thất. Mua nhiều sản phẩm để nhận ưu đãi combo đặc biệt.', 'giỏ hàng hỗn hợp, mixed cart, combo nghệ thuật, art bundle', FALSE, FALSE, '/cart/mixed-products', NULL, 'ShoppingCart', '{"@context": "https://schema.org", "@type": "ShoppingCart", "category": "Mixed Products"}', FALSE),

-- SEO for Orders (IDs 50-54)
('Đơn Hàng Tranh Nghệ Thuật #ORD-20260115-001', 'Chi tiết đơn hàng tranh nghệ thuật với mã ORD-20260115-001. Theo dõi trạng thái giao hàng, thông tin thanh toán và liên hệ hỗ trợ khách hàng.', 'đơn hàng tranh, order tracking, theo dõi đơn hàng, art order', FALSE, FALSE, '/orders/ORD-20260115-001', NULL, 'Order', '{"@context": "https://schema.org", "@type": "Order", "orderNumber": "ORD-20260115-001", "orderStatus": "Delivered"}', FALSE),
('Đơn Hàng Dụng Cụ Vẽ #ORD-20260116-002', 'Đơn hàng dụng cụ vẽ và họa cụ với mã ORD-20260116-002. Trạng thái hiện tại: đang xử lý. Dự kiến giao hàng trong 2-3 ngày làm việc.', 'đơn hàng dụng cụ vẽ, art supplies order, order status, giao hàng', FALSE, FALSE, '/orders/ORD-20260116-002', NULL, 'Order', '{"@context": "https://schema.org", "@type": "Order", "orderNumber": "ORD-20260116-002", "orderStatus": "Processing"}', FALSE),
('Đơn Hàng Decor Nội Thất #ORD-20260117-003', 'Đơn hàng sản phẩm trang trí nội thất mã ORD-20260117-003. Bao gồm đèn LED, tượng ceramic và khung tranh. Trạng thái: đã xác nhận.', 'đơn hàng decor, interior decoration order, home decor order, confirmed', FALSE, FALSE, '/orders/ORD-20260117-003', NULL, 'Order', '{"@context": "https://schema.org", "@type": "Order", "orderNumber": "ORD-20260117-003", "orderStatus": "Confirmed"}', FALSE),
('Lịch Sử Đơn Hàng Khách Hàng - Order History', 'Xem lịch sử tất cả đơn hàng đã mua: tranh nghệ thuật, dụng cụ vẽ, decor nội thất. Theo dõi trạng thái, tải hóa đơn và đánh giá sản phẩm.', 'lịch sử đơn hàng, order history, đơn hàng cũ, purchase history', FALSE, FALSE, '/orders/history', NULL, 'OrderHistory', '{"@context": "https://schema.org", "@type": "WebPage", "about": "Order History"}', FALSE),
('Đơn Hàng Combo Nghệ Thuật - Art Bundle Order', 'Đơn hàng combo sản phẩm nghệ thuật với giá ưu đãi đặc biệt. Bao gồm tranh + khung + dụng cụ vẽ. Tiết kiệm 20% so với mua lẻ.', 'đơn hàng combo, art bundle order, combo nghệ thuật, package deal', FALSE, FALSE, '/orders/art-bundle', NULL, 'Order', '{"@context": "https://schema.org", "@type": "Order", "category": "Art Bundle", "discount": "20%"}', FALSE),

-- SEO for Order State History (IDs 55-59)
('Lịch Sử Trạng Thái Đơn Hàng - Order Status History', 'Theo dõi chi tiết lịch sử thay đổi trạng thái đơn hàng từ khi đặt hàng đến giao thành công. Minh bạch trong quá trình xử lý và vận chuyển.', 'lịch sử trạng thái, order status history, theo dõi đơn hàng, order tracking', FALSE, FALSE, '/orders/status-history', NULL, 'OrderHistory', '{"@context": "https://schema.org", "@type": "TrackingDetails"}', FALSE),
('Đơn Hàng Đã Được Xác Nhận - Order Confirmed', 'Đơn hàng đã được xác nhận và đang chờ xử lý. Chúng tôi sẽ chuẩn bị hàng và thông báo khi sản phẩm sẵn sàng giao.', 'đơn hàng xác nhận, order confirmed, confirmed status, order processing', FALSE, FALSE, '/orders/confirmed-status', NULL, 'OrderStatus', '{"@context": "https://schema.org", "@type": "Order", "orderStatus": "OrderConfirmed"}', FALSE),
('Đơn Hàng Đang Xử Lý - Order Processing', 'Đơn hàng đang được xử lý và chuẩn bị. Nhân viên đang kiểm tra chất lượng sản phẩm và đóng gói cẩn thận cho quá trình vận chuyển.', 'đang xử lý, order processing, preparing order, order preparation', FALSE, FALSE, '/orders/processing-status', NULL, 'OrderStatus', '{"@context": "https://schema.org", "@type": "Order", "orderStatus": "OrderProcessing"}', FALSE),
('Đơn Hàng Đã Giao Vận Chuyển - Order Shipped', 'Đơn hàng đã được giao cho đơn vị vận chuyển. Quý khách có thể theo dõi tình trạng giao hàng qua mã vận đơn được cung cấp.', 'đã giao vận chuyển, order shipped, shipping status, in transit', FALSE, FALSE, '/orders/shipped-status', NULL, 'OrderStatus', '{"@context": "https://schema.org", "@type": "Order", "orderStatus": "OrderInTransit"}', FALSE),
('Đơn Hàng Giao Thành Công - Order Delivered', 'Đơn hàng đã được giao thành công đến địa chỉ của quý khách. Cảm ơn quý khách đã tin tưởng và mua sắm tại cửa hàng của chúng tôi.', 'giao thành công, order delivered, successful delivery, completed order', FALSE, FALSE, '/orders/delivered-status', NULL, 'OrderStatus', '{"@context": "https://schema.org", "@type": "Order", "orderStatus": "OrderDelivered"}', FALSE),

-- SEO for Payments (IDs 60-64)
('Thanh Toán Đơn Hàng Nghệ Thuật - Art Payment Gateway', 'Thanh toán an toàn cho đơn hàng tranh nghệ thuật với nhiều phương thức: COD, chuyển khoản, ví điện tử MoMo, ZaloPay, VNPay. Bảo mật SSL.', 'thanh toán tranh, art payment, payment gateway, secure payment', FALSE, FALSE, '/payments/art-checkout', NULL, 'PaymentMethod', '{"@context": "https://schema.org", "@type": "PaymentMethod", "paymentMethodId": "Multiple"}', FALSE),
('Thanh Toán MoMo - Mobile Wallet Payment', 'Thanh toán nhanh chóng và an toàn qua ví điện tử MoMo. Quét mã QR hoặc liên kết tài khoản để hoàn tất giao dịch mua tranh nghệ thuật.', 'thanh toán momo, momo payment, mobile wallet, ví điện tử', FALSE, FALSE, '/payments/momo-gateway', NULL, 'PaymentMethod', '{"@context": "https://schema.org", "@type": "PaymentMethod", "name": "MoMo E-wallet"}', FALSE),
('Thanh Toán VNPay - Banking Gateway', 'Thanh toán qua cổng VNPay với kết nối đa ngân hàng. An toàn, nhanh chóng, hỗ trợ thẻ ATM, Internet Banking và ví điện tử.', 'thanh toán vnpay, vnpay gateway, internet banking, atm payment', FALSE, FALSE, '/payments/vnpay-gateway', NULL, 'PaymentMethod', '{"@context": "https://schema.org", "@type": "PaymentMethod", "name": "VNPay Gateway"}', FALSE),
('Thanh Toán Khi Nhận Hàng - Cash On Delivery', 'Thanh toán COD (Cash On Delivery) - trả tiền mặt khi nhận hàng. Phương thức thanh toán thuận tiện, không cần thẻ ngân hàng hay ví điện tử.', 'cod payment, thanh toán khi nhận hàng, cash on delivery, trả tiền mặt', FALSE, FALSE, '/payments/cod-method', NULL, 'PaymentMethod', '{"@context": "https://schema.org", "@type": "PaymentMethod", "name": "Cash on Delivery"}', FALSE),
('Lịch Sử Thanh Toán - Payment History', 'Xem lịch sử tất cả giao dịch thanh toán: thành công, thất bại, hoàn tiền. Chi tiết mã giao dịch, phương thức và trạng thái thanh toán.', 'lịch sử thanh toán, payment history, transaction history, giao dịch', FALSE, FALSE, '/payments/history', NULL, 'PaymentHistory', '{"@context": "https://schema.org", "@type": "WebPage", "about": "Payment History"}', FALSE),

-- SEO for Shipments (IDs 65-69)
('Vận Chuyển Tranh Nghệ Thuật - Art Shipping Service', 'Dịch vụ vận chuyển tranh nghệ thuật chuyên nghiệp với đóng gói cẩn thận. Bảo hiểm hàng hóa, giao hàng an toàn đúng hẹn trên toàn quốc.', 'vận chuyển tranh, art shipping, giao hàng nghệ thuật, shipping service', TRUE, TRUE, '/shipping/art-delivery', NULL, 'DeliveryService', '{"@context": "https://schema.org", "@type": "DeliveryService", "serviceType": "Art Shipping"}', TRUE),
('Theo Dõi Vận Chuyển - Shipment Tracking', 'Theo dõi tình trạng vận chuyển đơn hàng theo thời gian thực. Cập nhật vị trí gói hàng và dự kiến thời gian giao đến địa chỉ của bạn.', 'theo dõi vận chuyển, shipment tracking, package tracking, delivery status', FALSE, FALSE, '/shipping/tracking', NULL, 'TrackingService', '{"@context": "https://schema.org", "@type": "TrackingDetails", "trackingNumber": "Variable"}', FALSE),
('Chính Sách Vận Chuyển - Shipping Policy', 'Chính sách vận chuyển: miễn phí từ 1 triệu đồng, phí ship 30k nội thành. Thời gian 2-5 ngày làm việc. Đóng gói cẩn thận, bảo hiểm hàng hóa.', 'chính sách vận chuyển, shipping policy, phí ship, delivery policy', TRUE, TRUE, '/shipping/policy', NULL, 'ShippingPolicy', '{"@context": "https://schema.org", "@type": "WebPage", "about": "Shipping Policy"}', TRUE),
('Vận Chuyển Nhanh Express - Express Delivery', 'Dịch vụ vận chuyển nhanh Express 24-48h cho đơn hàng khẩn cấp. Phù hợp với quà tặng hoặc sự kiện quan trọng, phí ship 50k toàn quốc.', 'vận chuyển nhanh, express delivery, giao hàng 24h, fast shipping', TRUE, TRUE, '/shipping/express', NULL, 'ExpressDelivery', '{"@context": "https://schema.org", "@type": "DeliveryService", "deliveryTime": "24-48 hours"}', TRUE),
('Vận Chuyển Miễn Phí - Free Shipping', 'Miễn phí vận chuyển cho đơn hàng từ 1.000.000đ trở lên. Áp dụng toàn quốc, giao hàng tiêu chuẩn 3-5 ngày làm việc.', 'miễn phí vận chuyển, free shipping, giao hàng miễn phí, free delivery', TRUE, TRUE, '/shipping/free', NULL, 'FreeShipping', '{"@context": "https://schema.org", "@type": "DeliveryService", "deliveryCharge": "Free for orders over 1M VND"}', TRUE),

-- SEO for Contact (IDs 70-72)
('Liên Hệ Art & Decor Store - Tư Vấn Nghệ Thuật', 'Liên hệ với Art & Decor Store để được tư vấn chọn tranh và trang trí phù hợp. Showroom tại TP.HCM và Hà Nội, hotline 24/7 hỗ trợ khách hàng.', 'liên hệ art decor, tư vấn tranh, contact art store, art consultation', TRUE, TRUE, '/contact/art-consultation', NULL, 'ContactPage', '{"@context": "https://schema.org", "@type": "ContactPage", "telephone": "+84-28-1234567"}', TRUE),
('Showroom Art & Decor TP.HCM - 123 Nguyễn Văn Linh Q7', 'Showroom Art & Decor tại TP.HCM: 123 Nguyễn Văn Linh, Quận 7. Trưng bày hàng ngàn tác phẩm tranh nghệ thuật và đồ trang trí cao cấp.', 'showroom hcm, art gallery saigon, tranh nghệ thuật tphcm, gallery q7', TRUE, TRUE, '/contact/showroom-hcm', NULL, 'LocalBusiness', '{"@context": "https://schema.org", "@type": "ArtGallery", "address": "123 Nguyễn Văn Linh, Q7, TP.HCM"}', TRUE),
('Showroom Art & Decor Hà Nội - 456 Trần Hưng Đạo', 'Showroom Art & Decor tại Hà Nội: 456 Trần Hưng Đạo, Hoàn Kiếm. Gallery nghệ thuật với không gian trưng bày hiện đại, tư vấn chuyên nghiệp.', 'showroom hanoi, art gallery hanoi, tranh nghệ thuật hà nội, gallery hoàn kiếm', TRUE, TRUE, '/contact/showroom-hanoi', NULL, 'LocalBusiness', '{"@context": "https://schema.org", "@type": "ArtGallery", "address": "456 Trần Hưng Đạo, Hoàn Kiếm, Hà Nội"}', TRUE),

-- SEO for Blogs (IDs 73-77)
('Blog: Xu Hướng Trang Trí Nội Thất Năm 2026', 'Khám phá xu hướng trang trí nội thất năm 2026: phong cách tối giản, màu sắc trung tính, kết hợp yếu tố thiên nhiên. Cẩm nang thiết kế hiện đại.', 'blog trang trí 2026, interior trends 2026, xu hướng nội thất, home decor trends', TRUE, TRUE, '/blog/interior-trends-2026', NULL, 'BlogPosting', '{"@context": "https://schema.org", "@type": "BlogPosting", "headline": "Interior Design Trends 2026"}', TRUE),
('Blog: Hướng Dẫn Chọn Tranh Phong Cảnh Phù Hợp', 'Hướng dẫn chi tiết cách chọn tranh phong cảnh phù hợp với không gian sống. Tips từ chuyên gia về kích thước, màu sắc và phong cách trang trí.', 'hướng dẫn chọn tranh, cách chọn tranh phong cảnh, landscape painting guide', TRUE, TRUE, '/blog/landscape-painting-guide', NULL, 'HowTo', '{"@context": "https://schema.org", "@type": "HowTo", "name": "How to Choose Landscape Paintings"}', TRUE),
('Blog: Triển Lãm Nghệ Thuật Hiện Đại Tại TP.HCM', 'Thông tin về triển lãm "Nghệ thuật hiện đại Việt Nam" tại Bảo tàng Mỹ thuật TP.HCM. 50 tác phẩm của các họa sĩ nổi tiếng từ 25/01 đến 25/02/2026.', 'triển lãm nghệ thuật, art exhibition hcm, modern art vietnam, fine arts museum', TRUE, TRUE, '/blog/modern-art-exhibition-hcm', NULL, 'Event', '{"@context": "https://schema.org", "@type": "Event", "name": "Modern Art Vietnam Exhibition"}', TRUE),
('Blog Video: Hướng Dẫn Vẽ Tranh Acrylic Cho Người Mới', 'Video hướng dẫn chi tiết cách vẽ tranh acrylic từ cơ bản đến nâng cao. Kỹ thuật pha màu, sử dụng cọ và tạo hiệu ứng đặc biệt cho người mới bắt đầu.', 'video vẽ tranh acrylic, acrylic painting tutorial, học vẽ tranh, painting guide', TRUE, TRUE, '/blog/acrylic-painting-tutorial-video', NULL, 'VideoObject', '{"@context": "https://schema.org", "@type": "VideoObject", "name": "Acrylic Painting Tutorial"}', TRUE),
('Blog Gallery: Bộ Sưu Tập Tranh Phong Cảnh Mùa Xuân', 'Thư viện hình ảnh bộ sưu tập tranh phong cảnh mùa xuân với gam màu tươi sáng. Khám phá vẻ đẹp thiên nhiên qua góc nhìn nghệ thuật đầy cảm hứng.', 'gallery tranh mùa xuân, spring landscape collection, art gallery spring', TRUE, TRUE, '/blog/spring-landscape-gallery', NULL, 'ImageGallery', '{"@context": "https://schema.org", "@type": "ImageGallery", "name": "Spring Landscape Collection"}', TRUE);

-- Insert sample shipping fees
INSERT INTO `SHIPPING_FEE` (`SHIPPING_FEE_TYPE_ID`, `MIN_ORDER_PRICE`, `MAX_ORDER_PRICE`, `SHIPPING_FEE_VALUE`, `SHIPPING_FEE_REMARK_EN`, `SHIPPING_FEE_REMARK`, `SHIPPING_FEE_ENABLED`) VALUES
(1, 0, 500000, 30000, 'Standard shipping under 500k', 'Phí vận chuyển tiêu chuẩn dưới 500k', TRUE),
(1, 500000, 1000000, 20000, 'Standard shipping 500k-1M', 'Phí vận chuyển tiêu chuẩn 500k-1M', TRUE),
(1, 1000000, 999999999, 0, 'Free standard shipping over 1M', 'Miễn phí vận chuyển tiêu chuẩn trên 1M', TRUE),
(2, 0, 999999999, 50000, 'Express shipping', 'Phí vận chuyển nhanh', TRUE),
(3, 0, 999999999, 0, 'Free shipping', 'Miễn phí vận chuyển', TRUE);

-- Insert Response Codes
INSERT INTO `RESPONSE_CODE` (`RESPONSE_CODE_NAME`, `RESPONSE_CODE_REMARK_EN`, `RESPONSE_CODE_REMARK`, `RESPONSE_CODE_ENABLED`) VALUES
('200', 'Success', 'Thành công', TRUE),
('201', 'Created successfully', 'Tạo thành công', TRUE),
('204', 'No content', 'Không có nội dung', TRUE),
('400', 'Bad request', 'Yêu cầu không hợp lệ', TRUE),
('401', 'Unauthorized', 'Không có quyền truy cập', TRUE),
('403', 'Access forbidden', 'Truy cập bị cấm', TRUE),
('404', 'Not found', 'Không tìm thấy', TRUE),
('409', 'Conflict occurred', 'Xung đột dữ liệu', TRUE),
('500', 'Internal server error', 'Lỗi máy chủ nội bộ', TRUE),
('503', 'Service unavailable', 'Dịch vụ không khả dụng', TRUE),
('1001', 'Invalid parameters', 'Tham số không hợp lệ', TRUE),
('1002', 'Missing required parameters', 'Thiếu tham số bắt buộc', TRUE),
('1003', 'Duplicate data', 'Dữ liệu trùng lặp', TRUE),
('1004', 'Data not found', 'Không tìm thấy dữ liệu', TRUE),
('1005', 'Updated successfully', 'Cập nhật thành công', TRUE),
('1006', 'Deleted successfully', 'Xóa thành công', TRUE);

-- =============================================
-- CREATE TRIGGERS FOR AUTO-UPDATE
-- =============================================

DELIMITER $$

CREATE TRIGGER `tr_update_review_count_like` 
AFTER INSERT ON `PRODUCT_REVIEW_LIKE`
FOR EACH ROW
BEGIN
    UPDATE `REVIEW` 
    SET `COUNT_LIKE` = `COUNT_LIKE` + 1 
    WHERE `REVIEW_ID` = NEW.`REVIEW_ID`;
END$$

CREATE TRIGGER `tr_decrease_review_count_like` 
AFTER DELETE ON `PRODUCT_REVIEW_LIKE`
FOR EACH ROW
BEGIN
    UPDATE `REVIEW` 
    SET `COUNT_LIKE` = `COUNT_LIKE` - 1 
    WHERE `REVIEW_ID` = OLD.`REVIEW_ID`;
END$$

CREATE TRIGGER `tr_update_discount_used_count` 
AFTER INSERT ON `ORDER`
FOR EACH ROW
BEGIN
    IF NEW.`DISCOUNT_ID` IS NOT NULL THEN
        UPDATE `DISCOUNT` 
        SET `USED_COUNT` = `USED_COUNT` + 1 
        WHERE `DISCOUNT_ID` = NEW.`DISCOUNT_ID`;
    END IF;
END$$

DELIMITER ;

-- =============================================
-- CREATE INDEXES FOR PERFORMANCE
-- =============================================

-- Additional performance indexes
CREATE INDEX `idx_product_created_dt` ON `PRODUCT`(`CREATED_DT`);
CREATE INDEX `idx_order_created_dt` ON `ORDER`(`CREATED_DT`);
CREATE INDEX `idx_review_created_dt` ON `REVIEW`(`CREATED_DT`);
CREATE INDEX `idx_blog_created_dt` ON `BLOG`(`CREATED_DT`);

-- Composite indexes for common queries
CREATE INDEX `idx_product_category_state` ON `PRODUCT`(`PRODUCT_CATEGORY_ID`, `PRODUCT_STATE_ID`);
CREATE INDEX `idx_product_price_range` ON `PRODUCT`(`PRODUCT_PRICE`, `STOCK_QUANTITY`);
CREATE INDEX `idx_review_product_rating` ON `REVIEW`(`PRODUCT_ID`, `RATING`, `IS_VISIBLE`);

-- =============================================
-- PAGE MANAGEMENT TABLES
-- =============================================

-- Table: PAGE_POSITION
CREATE TABLE `PAGE_POSITION` (
    `PAGE_POSITION_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_POSITION_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_POSITION_NAME` VARCHAR(100) NOT NULL,
    `PAGE_POSITION_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_POSITION_REMARK_EN` VARCHAR(256),
    `PAGE_POSITION_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_page_position_slug` (`PAGE_POSITION_SLUG`),
    INDEX `idx_page_position_enabled` (`PAGE_POSITION_ENABLED`)
);

-- Table: PAGE_GROUP
CREATE TABLE `PAGE_GROUP` (
    `PAGE_GROUP_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_GROUP_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_GROUP_NAME` VARCHAR(100) NOT NULL,
    `PAGE_GROUP_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_GROUP_REMARK_EN` VARCHAR(256),
    `PAGE_GROUP_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_page_group_slug` (`PAGE_GROUP_SLUG`),
    INDEX `idx_page_group_enabled` (`PAGE_GROUP_ENABLED`)
);

-- Table: PAGE
CREATE TABLE `PAGE` (
    `PAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_POSITION_ID` BIGINT NOT NULL,
    `PAGE_GROUP_ID` BIGINT NOT NULL,
    `TARGET_URL` VARCHAR(256),
    `PAGE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_NAME` VARCHAR(100) NOT NULL,
    `PAGE_CONTENT` LONGTEXT,
    `PAGE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_REMARK_EN` VARCHAR(256),
    `PAGE_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PAGE_POSITION_ID`) REFERENCES `PAGE_POSITION`(`PAGE_POSITION_ID`),
    FOREIGN KEY (`PAGE_GROUP_ID`) REFERENCES `PAGE_GROUP`(`PAGE_GROUP_ID`),
    INDEX `idx_page_slug` (`PAGE_SLUG`),
    INDEX `idx_page_position` (`PAGE_POSITION_ID`),
    INDEX `idx_page_group` (`PAGE_GROUP_ID`),
    INDEX `idx_page_enabled` (`PAGE_ENABLED`)
);

-- =============================================
-- SHOW TABLES AND SUMMARY
-- =============================================

SHOW TABLES;

-- Summary information
SELECT 
    'Database ART_AND_DECOR created successfully' AS Status,
    COUNT(*) AS TotalTables
FROM information_schema.tables 
WHERE table_schema = 'ART_AND_DECOR';
