-- =============================================
-- Database: ART_AND_DECOR
-- Description: E-commerce database for Art & Decor products (Schema Only)
-- Author: Generated for ArtAndDecor Project
-- Date: March 12, 2026
-- Version: 2.0 - Schema definitions only, all INSERT statements moved to INSERT_SAMPLE_DATA.sql
-- =============================================

-- Create and use database
DROP DATABASE IF EXISTS `ART_AND_DECOR`;

CREATE DATABASE IF NOT EXISTS `ART_AND_DECOR` 
CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `ART_AND_DECOR`;

-- =============================================
-- USER MANAGEMENT TABLES
-- =============================================

-- Table: USER_PROVIDER
CREATE TABLE `USER_PROVIDER` (
    `USER_PROVIDER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_PROVIDER_NAME` VARCHAR(50) NOT NULL UNIQUE,
    `USER_PROVIDER_DISPLAY_NAME` VARCHAR(256),
    `USER_PROVIDER_REMARK` VARCHAR(256) NOT NULL,
    `USER_PROVIDER_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_user_provider_name` (`USER_PROVIDER_NAME`)
);

-- Table: USER_ROLE
CREATE TABLE `USER_ROLE` (
    `USER_ROLE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ROLE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `USER_ROLE_DISPLAY_NAME` VARCHAR(256),
    `USER_ROLE_REMARK` VARCHAR(256) NOT NULL,
    `USER_ROLE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_user_role_name` (`USER_ROLE_NAME`)
);

-- Table: USER
CREATE TABLE `USER` (
    `USER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_PROVIDER_ID` BIGINT NOT NULL,
    `USER_ROLE_ID` BIGINT NOT NULL,
    `USER_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `USER_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PASSWORD` VARCHAR(255),
    `FIRST_NAME` VARCHAR(50),
    `LAST_NAME` VARCHAR(50),
    `PHONE_NUMBER` VARCHAR(15),
    `EMAIL` VARCHAR(100) NOT NULL UNIQUE,
    `IMAGE_AVATAR_NAME` VARCHAR(150),
    `SOCIAL_MEDIA` TEXT,
    `LAST_LOGIN_DT` DATETIME NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_PROVIDER_ID`) REFERENCES `USER_PROVIDER`(`USER_PROVIDER_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `USER_ROLE`(`USER_ROLE_ID`) ON DELETE RESTRICT,
    INDEX `idx_user_name` (`USER_NAME`),
    INDEX `idx_user_email` (`EMAIL`),
    INDEX `idx_user_phone` (`PHONE_NUMBER`)
);

-- =============================================
-- SEO MANAGEMENT TABLES
-- =============================================


-- Table: SEO_META
CREATE TABLE `SEO_META` (
    `SEO_META_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SEO_META_TITLE` VARCHAR(150) NOT NULL,
    `SEO_META_DESCRIPTION` VARCHAR(500) NOT NULL,
    `SEO_META_KEYWORDS` VARCHAR(300),
    `SEO_META_INDEX` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_FOLLOW` BOOLEAN NOT NULL DEFAULT TRUE,
    `SEO_META_CANONICAL_URL` VARCHAR(500),
    `SEO_META_IMAGE_NAME` VARCHAR(150),
    `SEO_META_SCHEMA_TYPE` VARCHAR(50),
    `SEO_META_CUSTOM_JSON` JSON,
    `SEO_META_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_seo_meta_title` (`SEO_META_TITLE`),
    INDEX `idx_seo_meta_canonical_url` (`SEO_META_CANONICAL_URL`),
    INDEX `idx_seo_meta_keywords` (`SEO_META_KEYWORDS`(100)),
    FULLTEXT INDEX `ft_seo_meta_search` (`SEO_META_TITLE`, `SEO_META_DESCRIPTION`, `SEO_META_KEYWORDS`)
);

-- =============================================
-- IMAGE MANAGEMENT TABLES
-- =============================================

-- Table: IMAGE_CATEGORY
-- IMAGE_CATEGORY table removed as per requirements

-- Table: IMAGE_FORMAT
-- IMAGE_FORMAT table removed as per requirements

-- Table: IMAGE
CREATE TABLE `IMAGE` (
    `IMAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `IMAGE_NAME` VARCHAR(150) NOT NULL,
    `IMAGE_DISPLAY_NAME` VARCHAR(64) NOT NULL,
    `IMAGE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `IMAGE_SIZE` VARCHAR(64) NOT NULL,
    `IMAGE_FORMAT` VARCHAR(10) NOT NULL,
    `PATH_FILE` VARCHAR(512) NOT NULL,
    `IMAGE_REMARK` VARCHAR(256),
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_image_name` (`IMAGE_NAME`),
    INDEX `idx_image_display_name` (`IMAGE_DISPLAY_NAME`),
    INDEX `idx_image_slug` (`IMAGE_SLUG`),
    INDEX `idx_image_path_file` (`PATH_FILE`)
);

-- =============================================
-- PRODUCT MANAGEMENT TABLES
-- =============================================

-- Table: PRODUCT_TYPE
CREATE TABLE `PRODUCT_TYPE` (
    `PRODUCT_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_TYPE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_TYPE_DISPLAY_NAME` VARCHAR(256),
    `PRODUCT_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `IMAGE_ID` BIGINT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_product_type_slug` (`PRODUCT_TYPE_SLUG`),
    INDEX `idx_product_type_name` (`PRODUCT_TYPE_NAME`),
    INDEX `idx_product_type_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_CATEGORY
CREATE TABLE `PRODUCT_CATEGORY` (
    `PRODUCT_CATEGORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_CATEGORY_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_DISPLAY_NAME` VARCHAR(256),
    `PRODUCT_CATEGORY_REMARK` VARCHAR(256) NOT NULL,
    `PRODUCT_CATEGORY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_CATEGORY_VISIBLE` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_TYPE_ID` BIGINT NOT NULL,
    `PRODUCT_CATEGORY_PARENT_ID` BIGINT NULL,
    `IMAGE_ID` BIGINT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`PRODUCT_TYPE_ID`) REFERENCES `PRODUCT_TYPE`(`PRODUCT_TYPE_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PRODUCT_CATEGORY_PARENT_ID`) REFERENCES `PRODUCT_CATEGORY`(`PRODUCT_CATEGORY_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE SET NULL,
    INDEX `idx_product_category_slug` (`PRODUCT_CATEGORY_SLUG`),
    INDEX `idx_product_category_name` (`PRODUCT_CATEGORY_NAME`),
    INDEX `idx_product_category_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_STATE
CREATE TABLE `PRODUCT_STATE` (
    `PRODUCT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_STATE_DISPLAY_NAME` VARCHAR(256),
    `PRODUCT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_product_state_name` (`PRODUCT_STATE_NAME`)
);

-- Table: PRODUCT_ATTR
CREATE TABLE `PRODUCT_ATTR` (
    `PRODUCT_ATTR_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ATTR_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_ATTR_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_ATTR_DISPLAY_NAME` VARCHAR(256),
    `PRODUCT_ATTR_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_product_attr_name` (`PRODUCT_ATTR_NAME`)
);

-- Table: PRODUCT
CREATE TABLE `PRODUCT` (
    `PRODUCT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_NAME` VARCHAR(100) NOT NULL UNIQUE,
    `PRODUCT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
	`PRODUCT_CODE` VARCHAR(64) NOT NULL UNIQUE,
    `PRODUCT_CATEGORY_ID` BIGINT NOT NULL,
    `PRODUCT_STATE_ID` BIGINT NOT NULL,
    `SOLD_QUANTITY` INT NOT NULL DEFAULT 0,
    `STOCK_QUANTITY` INT NOT NULL DEFAULT 0,
    `PRODUCT_DESCRIPTION` TEXT NOT NULL,
    `PRODUCT_PRICE` DECIMAL(15,2) NOT NULL,
    `PRODUCT_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PRODUCT_FEATURED` BOOLEAN NOT NULL DEFAULT FALSE,
    `PRODUCT_HIGHLIGHTED` BOOLEAN NOT NULL DEFAULT FALSE,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_CATEGORY_ID`) REFERENCES `PRODUCT_CATEGORY`(`PRODUCT_CATEGORY_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PRODUCT_STATE_ID`) REFERENCES `PRODUCT_STATE`(`PRODUCT_STATE_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_product_name` (`PRODUCT_NAME`),
    INDEX `idx_product_slug` (`PRODUCT_SLUG`),
    INDEX `idx_product_price` (`PRODUCT_PRICE`),
    INDEX `idx_product_stock` (`STOCK_QUANTITY`),
    INDEX `idx_product_seo_meta` (`SEO_META_ID`)
);

-- Table: PRODUCT_IMAGE
CREATE TABLE `PRODUCT_IMAGE` (
    `PRODUCT_IMAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `IMAGE_ID` BIGINT NOT NULL,
    `PRODUCT_IMAGE_PRIMARY` BOOLEAN NOT NULL DEFAULT FALSE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE RESTRICT,
    UNIQUE KEY `idx_product_image_unique` (`PRODUCT_ID`, `IMAGE_ID`)
);

-- Table: PRODUCT_ATTRIBUTE
CREATE TABLE `PRODUCT_ATTRIBUTE` (
    `PRODUCT_ATTRIBUTE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` BIGINT NOT NULL,
    `PRODUCT_ATTR_ID` BIGINT NOT NULL,
    `PRODUCT_ATTRIBUTE_VALUE` VARCHAR(256) NOT NULL,
    `PRODUCT_ATTRIBUTE_QUANTITY` INT NOT NULL DEFAULT 0,
    `PRODUCT_ATTRIBUTE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ATTR_ID`) REFERENCES `PRODUCT_ATTR`(`PRODUCT_ATTR_ID`) ON DELETE RESTRICT,
    UNIQUE KEY `idx_product_attribute_value_unique` (`PRODUCT_ID`, `PRODUCT_ATTR_ID`, `PRODUCT_ATTRIBUTE_VALUE`),
    INDEX `idx_product_attribute_quantity` (`PRODUCT_ATTRIBUTE_QUANTITY`)
);

-- =============================================
-- REVIEW SYSTEM TABLES
-- =============================================

-- Table: REVIEW
CREATE TABLE `REVIEW` (
    `REVIEW_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `PARENT_REVIEW_ID` BIGINT,
    `ROOT_REVIEW_ID` BIGINT,
    `REVIEW_LEVEL` INT NOT NULL DEFAULT 0,
    `RATING` TINYINT NOT NULL CHECK (`RATING` BETWEEN 1 AND 5),
    `REVIEW_CONTENT` TEXT NOT NULL,
    `COUNT_LIKE` INT NOT NULL DEFAULT 0,
    `IS_VISIBLE` BOOLEAN NOT NULL DEFAULT TRUE,
    `IS_DELETED` BOOLEAN NOT NULL DEFAULT FALSE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PARENT_REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`ROOT_REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`) ON DELETE CASCADE,
    INDEX `idx_review_product` (`PRODUCT_ID`),
    INDEX `idx_review_user` (`USER_ID`),
    INDEX `idx_review_rating` (`RATING`)
);

-- Table: PRODUCT_REVIEW_LIKE
CREATE TABLE `PRODUCT_REVIEW_LIKE` (
    `PRODUCT_REVIEW_LIKE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `REVIEW_ID` BIGINT NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW`(`REVIEW_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE RESTRICT,
    UNIQUE KEY `idx_user_review_like_unique` (`USER_ID`, `REVIEW_ID`)
);

-- =============================================
-- CART SYSTEM TABLES
-- =============================================

-- Table: CART_STATE
CREATE TABLE `CART_STATE` (
    `CART_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `CART_STATE_DISPLAY_NAME` VARCHAR(256),
    `CART_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CART_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_cart_state_name` (`CART_STATE_NAME`)
);

-- Table: CART
CREATE TABLE `CART` (
    `CART_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `USER_ID` BIGINT NULL,
    `SESSION_ID` VARCHAR(100),
    `CART_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `CART_STATE_ID` BIGINT NOT NULL,
    `TOTAL_QUANTITY` INT NOT NULL DEFAULT 0,
    `CART_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`CART_STATE_ID`) REFERENCES `CART_STATE`(`CART_STATE_ID`) ON DELETE RESTRICT,
    INDEX `idx_cart_user` (`USER_ID`),
    INDEX `idx_cart_session` (`SESSION_ID`),
    INDEX `idx_cart_slug` (`CART_SLUG`)
);

-- Table: CART_ITEM_STATE
CREATE TABLE `CART_ITEM_STATE` (
    `CART_ITEM_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_ITEM_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `CART_ITEM_STATE_DISPLAY_NAME` VARCHAR(256),
    `CART_ITEM_STATE_REMARK` VARCHAR(256) NOT NULL,
    `CART_ITEM_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_cart_item_state_name` (`CART_ITEM_STATE_NAME`)
);

-- Table: CART_ITEM
CREATE TABLE `CART_ITEM` (
    `CART_ITEM_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `CART_ITEM_QUANTITY` INT NOT NULL DEFAULT 1,
    `CART_ITEM_TOTAL_PRICE` DECIMAL(15,2) NOT NULL,
    `CART_ITEM_STATE_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`CART_ID`) REFERENCES `CART`(`CART_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`CART_ITEM_STATE_ID`) REFERENCES `CART_ITEM_STATE`(`CART_ITEM_STATE_ID`) ON DELETE RESTRICT,
    INDEX `idx_cart_item_cart` (`CART_ID`),
    INDEX `idx_cart_item_product` (`PRODUCT_ID`)
);

-- Table: CART_ITEM_ATTRIBUTE (Simplified mapping table for cart item attributes)
CREATE TABLE `CART_ITEM_ATTRIBUTE` (
    `CART_ITEM_ATTRIBUTE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CART_ITEM_ID` BIGINT NOT NULL,
    `PRODUCT_ATTRIBUTE_ID` BIGINT NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`CART_ITEM_ID`) REFERENCES `CART_ITEM`(`CART_ITEM_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`PRODUCT_ATTRIBUTE_ID`) REFERENCES `PRODUCT_ATTRIBUTE`(`PRODUCT_ATTRIBUTE_ID`) ON DELETE CASCADE,
    INDEX `idx_cart_item_attr_cart_item` (`CART_ITEM_ID`),
    INDEX `idx_cart_item_attr_product_attr` (`PRODUCT_ATTRIBUTE_ID`),
    UNIQUE KEY `idx_cart_item_product_attribute_unique` (`CART_ITEM_ID`, `PRODUCT_ATTRIBUTE_ID`)
);

-- =============================================
-- ORDER MANAGEMENT TABLES
-- =============================================

-- Table: ORDER_STATE
CREATE TABLE `ORDER_STATE` (
    `ORDER_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `ORDER_STATE_DISPLAY_NAME` VARCHAR(256),
    `ORDER_STATE_REMARK` VARCHAR(256) NOT NULL,
    `ORDER_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_order_state_name` (`ORDER_STATE_NAME`)
);

-- Table: DISCOUNT_TYPE
CREATE TABLE `DISCOUNT_TYPE` (
    `DISCOUNT_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `DISCOUNT_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `DISCOUNT_TYPE_DISPLAY_NAME` VARCHAR(256),
    `DISCOUNT_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `DISCOUNT_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_discount_type_name` (`DISCOUNT_TYPE_NAME`)
);

-- Table: DISCOUNT
CREATE TABLE `DISCOUNT` (
    `DISCOUNT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `DISCOUNT_CODE` VARCHAR(100) NOT NULL UNIQUE,
    `DISCOUNT_NAME` VARCHAR(64) NOT NULL,
    `DISCOUNT_TYPE_ID` BIGINT NOT NULL,
    `DISCOUNT_VALUE` DECIMAL(15,2) NOT NULL,
    `MAX_DISCOUNT_AMOUNT` DECIMAL(15,2) NOT NULL,
    `MIN_ORDER_AMOUNT` DECIMAL(15,2) NOT NULL,
    `START_AT` DATETIME NOT NULL,
    `END_AT` DATETIME NOT NULL,
    `TOTAL_USAGE_LIMIT` INT NOT NULL,
    `USED_COUNT` INT NOT NULL DEFAULT 0,
    `IS_ACTIVE` BOOLEAN NOT NULL DEFAULT TRUE,
    `DISCOUNT_DISPLAY_NAME` VARCHAR(256),
    `DISCOUNT_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`DISCOUNT_TYPE_ID`) REFERENCES `DISCOUNT_TYPE`(`DISCOUNT_TYPE_ID`) ON DELETE RESTRICT,
    INDEX `idx_discount_code` (`DISCOUNT_CODE`),
    INDEX `idx_discount_dates` (`START_AT`, `END_AT`)
);

-- Table: ORDERS (changed from ORDER to avoid MySQL reserved keyword)
CREATE TABLE `ORDERS` (
	`ORDER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,

	-- USER (có thể NULL nếu guest checkout)
	`USER_ID` BIGINT NULL,

	`ORDER_CODE` VARCHAR(50) NOT NULL UNIQUE,
	`ORDER_SLUG` VARCHAR(64) NOT NULL UNIQUE,

	`ORDER_STATE_ID` BIGINT NOT NULL,

	-- Snapshot thông tin discount (từ DISCOUNT và DISCOUNT_TYPE tables)
	`DISCOUNT_CODE` VARCHAR(50) NULL,
	`DISCOUNT_TYPE` VARCHAR(100) NULL,
	`DISCOUNT_VALUE` DECIMAL(15,2) NULL,

	-- Snapshot thông tin khách hàng đặt hàng
	`CUSTOMER_NAME` VARCHAR(150) NULL,
	`CUSTOMER_PHONE_NUMBER` VARCHAR(15) NULL,
	`CUSTOMER_EMAIL` VARCHAR(100) NULL,
	`CUSTOMER_ADDRESS` TEXT NULL,

	-- Snapshot thông tin người nhận
	`RECEIVER_NAME` VARCHAR(150) NULL,
	`RECEIVER_PHONE` VARCHAR(20) NULL,
	`RECEIVER_EMAIL` VARCHAR(150) NULL,
	`ADDRESS_LINE` VARCHAR(255) NULL,
	`CITY` VARCHAR(100) NULL,
	`WARD` VARCHAR(100) NULL,
	`COUNTRY` VARCHAR(100) NULL,

	-- Tách tiền rõ ràng
	`SUBTOTAL_AMOUNT` DECIMAL(15,2) NOT NULL,
	`DISCOUNT_AMOUNT` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`SHIPPING_FEE_AMOUNT` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`TOTAL_AMOUNT` DECIMAL(15,2) NOT NULL,

	`ORDER_NOTE` TEXT NULL,

	`CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (`USER_ID`)
		REFERENCES `USER`(`USER_ID`) ON DELETE SET NULL,

	FOREIGN KEY (`ORDER_STATE_ID`)
		REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`) ON DELETE RESTRICT,

	INDEX `idx_order_code` (`ORDER_CODE`),
	INDEX `idx_order_user` (`USER_ID`),
	INDEX `idx_order_state` (`ORDER_STATE_ID`),
	INDEX `idx_order_created_dt` (`CREATED_DT`)
);

-- Table: ORDER_STATE_HISTORY
CREATE TABLE `ORDER_STATE_HISTORY` (
	`ORDER_STATE_HISTORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,

	`ORDER_ID` BIGINT NOT NULL,

	`OLD_STATE_ID` BIGINT NOT NULL,
	`NEW_STATE_ID` BIGINT NOT NULL,

	`CHANGED_BY_USER_ID` BIGINT NULL,

	`CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (`ORDER_ID`)
		REFERENCES `ORDERS`(`ORDER_ID`) ON DELETE CASCADE,

	FOREIGN KEY (`OLD_STATE_ID`)
		REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`) ON DELETE RESTRICT,

	FOREIGN KEY (`NEW_STATE_ID`)
		REFERENCES `ORDER_STATE`(`ORDER_STATE_ID`) ON DELETE RESTRICT,

	FOREIGN KEY (`CHANGED_BY_USER_ID`)
		REFERENCES `USER`(`USER_ID`) ON DELETE SET NULL,

	INDEX `idx_order_history_order` (`ORDER_ID`)
);

-- Table: ORDER_ITEM
CREATE TABLE `ORDER_ITEM` (
	`ORDER_ITEM_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`ORDER_ID` BIGINT NOT NULL,

	-- Snapshot product information
	`PRODUCT_ID` BIGINT NOT NULL,
	`PRODUCT_NAME` VARCHAR(255) NOT NULL,
	`PRODUCT_CODE` VARCHAR(64) NOT NULL,
	`PRODUCT_CATEGORY_NAME` VARCHAR(100) NOT NULL,
	`PRODUCT_TYPE_NAME` VARCHAR(100) NOT NULL,
	`PRODUCT_ATTR_JSON` JSON NULL,

	`UNIT_PRICE` DECIMAL(15,2) NOT NULL,
	`QUANTITY` INT NOT NULL,

	`TOTAL_PRICE` DECIMAL(15,2) NOT NULL,

	`CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (`ORDER_ID`)
		REFERENCES `ORDERS`(`ORDER_ID`) ON DELETE CASCADE,

	FOREIGN KEY (`PRODUCT_ID`)
		REFERENCES `PRODUCT`(`PRODUCT_ID`) ON DELETE RESTRICT,

	INDEX `idx_order_item_order` (`ORDER_ID`),
	INDEX `idx_order_item_product` (`PRODUCT_ID`)
);



-- =============================================
-- PAYMENT SYSTEM TABLES
-- =============================================

-- Table: PAYMENT_METHOD
CREATE TABLE `PAYMENT_METHOD` (
    `PAYMENT_METHOD_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAYMENT_METHOD_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_METHOD_DISPLAY_NAME` VARCHAR(256),
    `PAYMENT_METHOD_REMARK` VARCHAR(256) NOT NULL,
    `PAYMENT_METHOD_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_payment_method_name` (`PAYMENT_METHOD_NAME`)
);

-- Table: PAYMENT_STATE
CREATE TABLE `PAYMENT_STATE` (
    `PAYMENT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAYMENT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_STATE_DISPLAY_NAME` VARCHAR(256),
    `PAYMENT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `PAYMENT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_payment_state_name` (`PAYMENT_STATE_NAME`)
);

-- Table: PAYMENT
CREATE TABLE `PAYMENT` (
    `PAYMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `PAYMENT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAYMENT_METHOD_ID` BIGINT NOT NULL,
    `PAYMENT_STATE_ID` BIGINT NOT NULL,
    `AMOUNT` DECIMAL(15,2) NOT NULL,
    `TRANSACTION_ID` VARCHAR(100) NOT NULL,
    `PAYMENT_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `ORDERS`(`ORDER_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PAYMENT_METHOD_ID`) REFERENCES `PAYMENT_METHOD`(`PAYMENT_METHOD_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PAYMENT_STATE_ID`) REFERENCES `PAYMENT_STATE`(`PAYMENT_STATE_ID`) ON DELETE RESTRICT,
    INDEX `idx_payment_order` (`ORDER_ID`),
    INDEX `idx_payment_slug` (`PAYMENT_SLUG`),
    INDEX `idx_payment_transaction` (`TRANSACTION_ID`)
);

-- =============================================
-- SHIPPING SYSTEM TABLES
-- =============================================

-- Table: SHIPPING_FEE_TYPE
CREATE TABLE `SHIPPING_FEE_TYPE` (
    `SHIPPING_FEE_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPPING_FEE_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `SHIPPING_FEE_TYPE_DISPLAY_NAME` VARCHAR(256),
    `SHIPPING_FEE_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPPING_FEE_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_shipping_fee_type_name` (`SHIPPING_FEE_TYPE_NAME`)
);

-- Table: SHIPPING_FEE
CREATE TABLE `SHIPPING_FEE` (
    `SHIPPING_FEE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPPING_FEE_TYPE_ID` BIGINT NOT NULL,
    `MIN_ORDER_PRICE` DECIMAL(15,2) NOT NULL,
    `MAX_ORDER_PRICE` DECIMAL(15,2) NOT NULL,
    `SHIPPING_FEE_VALUE` DECIMAL(15,2) NOT NULL,
    `SHIPPING_FEE_DISPLAY_NAME` VARCHAR(256),
    `SHIPPING_FEE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPPING_FEE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SHIPPING_FEE_TYPE_ID`) REFERENCES `SHIPPING_FEE_TYPE`(`SHIPPING_FEE_TYPE_ID`) ON DELETE RESTRICT,
    INDEX `idx_shipping_fee_price_range` (`MIN_ORDER_PRICE`, `MAX_ORDER_PRICE`)
);

-- Table: SHIPMENT_STATE
CREATE TABLE `SHIPMENT_STATE` (
    `SHIPMENT_STATE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `SHIPMENT_STATE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `SHIPMENT_STATE_DISPLAY_NAME` VARCHAR(256),
    `SHIPMENT_STATE_REMARK` VARCHAR(256) NOT NULL,
    `SHIPMENT_STATE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_shipment_state_name` (`SHIPMENT_STATE_NAME`)
);

-- Table: SHIPMENT
CREATE TABLE `SHIPMENT` (
	`SHIPMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
	`ORDER_ID` BIGINT NOT NULL,
	`SHIPMENT_CODE` VARCHAR(64) NOT NULL UNIQUE,
	`SHIPMENT_STATE_ID` BIGINT NOT NULL,

	-- Snapshot receiver
	`RECEIVER_NAME` VARCHAR(150) NOT NULL,
	`RECEIVER_PHONE` VARCHAR(20) NOT NULL,
	`RECEIVER_EMAIL` VARCHAR(150) NULL,

	`ADDRESS_LINE` VARCHAR(255) NOT NULL,
	`CITY` VARCHAR(100) NOT NULL,
	`WARD` VARCHAR(100) NULL,
	`COUNTRY` VARCHAR(100) NOT NULL,

	-- Snapshot shipping fee
	`SHIPPING_FEE_AMOUNT` DECIMAL(15,2) NOT NULL DEFAULT 0,

	-- Timeline
	`SHIPPED_AT` DATETIME NULL,
	`DELIVERED_AT` DATETIME NULL,
	`SHIPMENT_REMARK` VARCHAR(256) NULL,

	`CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (`ORDER_ID`)
		REFERENCES `ORDERS`(`ORDER_ID`) ON DELETE CASCADE,

	FOREIGN KEY (`SHIPMENT_STATE_ID`)
		REFERENCES `SHIPMENT_STATE`(`SHIPMENT_STATE_ID`) ON DELETE RESTRICT,

	INDEX `idx_shipment_order` (`ORDER_ID`),
	INDEX `idx_shipment_state` (`SHIPMENT_STATE_ID`)
);

-- =============================================
-- CONTENT MANAGEMENT TABLES
-- =============================================

-- Table: BLOG_TYPE
CREATE TABLE `BLOG_TYPE` (
    `BLOG_TYPE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_TYPE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_TYPE_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_TYPE_DISPLAY_NAME` VARCHAR(256),
    `BLOG_TYPE_REMARK` VARCHAR(256) NOT NULL,
    `BLOG_TYPE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `IMAGE_ID` BIGINT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_type_slug` (`BLOG_TYPE_SLUG`),
    INDEX `idx_blog_type_seo_meta` (`SEO_META_ID`)
);

-- Table: BLOG_CATEGORY
CREATE TABLE `BLOG_CATEGORY` (
    `BLOG_CATEGORY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_CATEGORY_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CATEGORY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CATEGORY_DISPLAY_NAME` VARCHAR(256),
    `BLOG_CATEGORY_REMARK` VARCHAR(256) NOT NULL,
    `BLOG_CATEGORY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `BLOG_TYPE_ID` BIGINT NULL,
    `IMAGE_ID` BIGINT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`BLOG_TYPE_ID`) REFERENCES `BLOG_TYPE`(`BLOG_TYPE_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_category_slug` (`BLOG_CATEGORY_SLUG`),
    INDEX `idx_blog_category_seo_meta` (`SEO_META_ID`)
);

-- Table: BLOG
CREATE TABLE `BLOG` (
    `BLOG_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `BLOG_CATEGORY_ID` BIGINT NOT NULL,
    `BLOG_TITLE` VARCHAR(256) NOT NULL,
    `BLOG_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `BLOG_CONTENT` LONGTEXT NOT NULL,
    `BLOG_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `BLOG_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `IMAGE_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`BLOG_CATEGORY_ID`) REFERENCES `BLOG_CATEGORY`(`BLOG_CATEGORY_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    FOREIGN KEY (`IMAGE_ID`) REFERENCES `IMAGE`(`IMAGE_ID`) ON DELETE SET NULL,
    INDEX `idx_blog_slug` (`BLOG_SLUG`),
    INDEX `idx_blog_title` (`BLOG_TITLE`),
    INDEX `idx_blog_seo_meta` (`SEO_META_ID`),
    INDEX `idx_blog_image` (`IMAGE_ID`)
);

-- =============================================
-- CONFIGURATION TABLES
-- =============================================

-- Table: CONTACT
CREATE TABLE `CONTACT` (
    `CONTACT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CONTACT_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `CONTACT_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `CONTACT_ADDRESS` VARCHAR(256) NOT NULL,
    `CONTACT_EMAIL` VARCHAR(64) NOT NULL,
    `CONTACT_PHONE` VARCHAR(15) NOT NULL,
    `CONTACT_FANPAGE` VARCHAR(256),
    `CONTACT_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CONTACT_REMARK` VARCHAR(256) NOT NULL,
    `SEO_META_ID` BIGINT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`SEO_META_ID`) REFERENCES `SEO_META`(`SEO_META_ID`) ON DELETE SET NULL,
    INDEX `idx_contact_email` (`CONTACT_EMAIL`),
    INDEX `idx_contact_slug` (`CONTACT_SLUG`),
    INDEX `idx_contact_seo_meta` (`SEO_META_ID`)
);

-- Table: POLICY
CREATE TABLE `POLICY` (
    `POLICY_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `POLICY_NAME` VARCHAR(64) NOT NULL UNIQUE,
    `POLICY_SLUG` VARCHAR(64),
    `POLICY_VALUE` TEXT NOT NULL,
    `POLICY_DISPLAY_NAME` VARCHAR(256),
    `POLICY_REMARK` VARCHAR(256) NOT NULL,
    `POLICY_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_policy_name` (`POLICY_NAME`),
    INDEX `idx_policy_slug` (`POLICY_SLUG`)
);

-- =============================================
-- PAGE MANAGEMENT TABLES
-- =============================================

-- Table: PAGE_POSITION
CREATE TABLE `PAGE_POSITION` (
    `PAGE_POSITION_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_POSITION_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_POSITION_NAME` VARCHAR(100) NOT NULL,
    `PAGE_POSITION_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_POSITION_DISPLAY_NAME` VARCHAR(256),
    `PAGE_POSITION_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_page_position_slug` (`PAGE_POSITION_SLUG`),
    INDEX `idx_page_position_enabled` (`PAGE_POSITION_ENABLED`)
);

-- Table: PAGE_GROUP
CREATE TABLE `PAGE_GROUP` (
    `PAGE_GROUP_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_GROUP_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_GROUP_NAME` VARCHAR(100) NOT NULL,
    `PAGE_GROUP_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_GROUP_DISPLAY_NAME` VARCHAR(256),
    `PAGE_GROUP_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_page_group_slug` (`PAGE_GROUP_SLUG`),
    INDEX `idx_page_group_enabled` (`PAGE_GROUP_ENABLED`)
);

-- Table: PAGE
CREATE TABLE `PAGE` (
    `PAGE_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `PAGE_POSITION_ID` BIGINT NOT NULL,
    `PAGE_GROUP_ID` BIGINT NOT NULL,
    `TARGET_URL` VARCHAR(256),
    `PAGE_SLUG` VARCHAR(64) NOT NULL UNIQUE,
    `PAGE_NAME` VARCHAR(100) NOT NULL,
    `PAGE_CONTENT` LONGTEXT,
    `PAGE_ENABLED` BOOLEAN NOT NULL DEFAULT TRUE,
    `PAGE_DISPLAY_NAME` VARCHAR(256),
    `PAGE_REMARK` VARCHAR(256) NOT NULL,
    `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `MODIFIED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`PAGE_POSITION_ID`) REFERENCES `PAGE_POSITION`(`PAGE_POSITION_ID`) ON DELETE RESTRICT,
    FOREIGN KEY (`PAGE_GROUP_ID`) REFERENCES `PAGE_GROUP`(`PAGE_GROUP_ID`) ON DELETE RESTRICT,
    INDEX `idx_page_slug` (`PAGE_SLUG`),
    INDEX `idx_page_position` (`PAGE_POSITION_ID`),
    INDEX `idx_page_group` (`PAGE_GROUP_ID`),
    INDEX `idx_page_enabled` (`PAGE_ENABLED`)
);

-- =============================================
-- PRODUCT STOCK MANAGEMENT TRIGGERS
-- =============================================

-- These triggers automatically update PRODUCT.STOCK_QUANTITY
-- when PRODUCT_ATTRIBUTE quantities change

DELIMITER $$

-- Trigger for INSERT - updates product stock when new attribute added
CREATE TRIGGER `trg_product_attribute_insert_update_stock`
    AFTER INSERT ON `PRODUCT_ATTRIBUTE`
    FOR EACH ROW
BEGIN
    UPDATE `PRODUCT` 
    SET `STOCK_QUANTITY` = (
        SELECT COALESCE(SUM(`PRODUCT_ATTRIBUTE_QUANTITY`), 0)
        FROM `PRODUCT_ATTRIBUTE` 
        WHERE `PRODUCT_ID` = NEW.`PRODUCT_ID` 
        AND `PRODUCT_ATTRIBUTE_ENABLED` = TRUE
    )
    WHERE `PRODUCT_ID` = NEW.`PRODUCT_ID`;
END$$

-- Trigger for UPDATE - updates product stock when attribute quantity changes
CREATE TRIGGER `trg_product_attribute_update_update_stock`
    AFTER UPDATE ON `PRODUCT_ATTRIBUTE`
    FOR EACH ROW
BEGIN
    UPDATE `PRODUCT` 
    SET `STOCK_QUANTITY` = (
        SELECT COALESCE(SUM(`PRODUCT_ATTRIBUTE_QUANTITY`), 0)
        FROM `PRODUCT_ATTRIBUTE` 
        WHERE `PRODUCT_ID` = NEW.`PRODUCT_ID` 
        AND `PRODUCT_ATTRIBUTE_ENABLED` = TRUE
    )
    WHERE `PRODUCT_ID` = NEW.`PRODUCT_ID`;
    
    -- Also update old product if PRODUCT_ID changed (rare case)
    IF OLD.`PRODUCT_ID` != NEW.`PRODUCT_ID` THEN
        UPDATE `PRODUCT` 
        SET `STOCK_QUANTITY` = (
            SELECT COALESCE(SUM(`PRODUCT_ATTRIBUTE_QUANTITY`), 0)
            FROM `PRODUCT_ATTRIBUTE` 
            WHERE `PRODUCT_ID` = OLD.`PRODUCT_ID` 
            AND `PRODUCT_ATTRIBUTE_ENABLED` = TRUE
        )
        WHERE `PRODUCT_ID` = OLD.`PRODUCT_ID`;
    END IF;
END$$

-- Trigger for DELETE - updates product stock when attribute removed
CREATE TRIGGER `trg_product_attribute_delete_update_stock`
    AFTER DELETE ON `PRODUCT_ATTRIBUTE`
    FOR EACH ROW
BEGIN
    UPDATE `PRODUCT` 
    SET `STOCK_QUANTITY` = (
        SELECT COALESCE(SUM(`PRODUCT_ATTRIBUTE_QUANTITY`), 0)
        FROM `PRODUCT_ATTRIBUTE` 
        WHERE `PRODUCT_ID` = OLD.`PRODUCT_ID` 
        AND `PRODUCT_ATTRIBUTE_ENABLED` = TRUE
    )
    WHERE `PRODUCT_ID` = OLD.`PRODUCT_ID`;
END$$

DELIMITER ;

-- =============================================
-- HELPFUL VIEWS FOR STOCK MANAGEMENT
-- =============================================

-- View to see product stock summary
CREATE VIEW `v_product_stock_summary` AS
SELECT 
    p.`PRODUCT_ID`,
    p.`PRODUCT_NAME`,
    p.`PRODUCT_CODE`,
    p.`STOCK_QUANTITY` AS `TOTAL_STOCK`,
    COUNT(pa.`PRODUCT_ATTRIBUTE_ID`) as `ATTRIBUTE_COUNT`,
    SUM(CASE WHEN pa.`PRODUCT_ATTRIBUTE_ENABLED` = TRUE THEN pa.`PRODUCT_ATTRIBUTE_QUANTITY` ELSE 0 END) as `CALCULATED_STOCK`
FROM `PRODUCT` p
LEFT JOIN `PRODUCT_ATTRIBUTE` pa ON p.`PRODUCT_ID` = pa.`PRODUCT_ID`
GROUP BY p.`PRODUCT_ID`, p.`PRODUCT_NAME`, p.`PRODUCT_CODE`, p.`STOCK_QUANTITY`;

-- View to see detailed attribute quantities  
CREATE VIEW `v_product_attribute_detail` AS
SELECT 
    p.`PRODUCT_ID`,
    p.`PRODUCT_NAME`,
    p.`PRODUCT_CODE`,
    pat.`PRODUCT_ATTR_NAME` as `ATTRIBUTE_TYPE`,
    pa.`PRODUCT_ATTRIBUTE_VALUE` as `ATTRIBUTE_VALUE`,
    pa.`PRODUCT_ATTRIBUTE_QUANTITY`,
    pa.`PRODUCT_ATTRIBUTE_ENABLED`
FROM `PRODUCT` p
JOIN `PRODUCT_ATTRIBUTE` pa ON p.`PRODUCT_ID` = pa.`PRODUCT_ID`
JOIN `PRODUCT_ATTR` pat ON pa.`PRODUCT_ATTR_ID` = pat.`PRODUCT_ATTR_ID`
ORDER BY p.`PRODUCT_ID`, pat.`PRODUCT_ATTR_NAME`, pa.`PRODUCT_ATTRIBUTE_VALUE`;

-- =============================================
-- SCHEMA CREATION COMPLETE
-- =============================================
-- Database now includes:
-- 1. PRODUCT_ATTRIBUTE_QUANTITY field for inventory management per attribute
-- 2. Automatic triggers to update PRODUCT.STOCK_QUANTITY from attribute totals
-- 3. Views for easy stock monitoring and reporting
-- 4. Support for multiple attribute values per product (e.g., multiple colors/sizes)
-- 
-- Usage:
-- - PRODUCT.STOCK_QUANTITY = Sum of all enabled PRODUCT_ATTRIBUTE.PRODUCT_ATTRIBUTE_QUANTITY
-- - Each attribute variant can have its own stock quantity
-- - Triggers ensure data consistency automatically
-- =============================================