-- Thêm cột nếu chưa tồn tại (MySQL 8+)
ALTER TABLE `PRODUCT_ATTRIBUTE`
ADD COLUMN IF NOT EXISTS `PRODUCT_ATTRIBUTE_PRICE` DECIMAL(15, 2) NULL DEFAULT NULL
AFTER `PRODUCT_ATTRIBUTE_QUANTITY`;

-- Thêm index nếu chưa tồn tại
CREATE INDEX `idx_product_attribute_price`
ON `PRODUCT_ATTRIBUTE` (`PRODUCT_ATTRIBUTE_PRICE`);